### ISSUE TITLE
Interactions between bodies

### ISSUE THREAD

**Issue by rbh007720** [peridigm/peridigm#101]
Hi,

I am wondering how to enable the contact model between contacting bodies only, that is, there is no contact force within each body. So that I can model the bodies using correspondence material models, and the interactions between them are specified by the contact model, while there is no self-contact within them. How can I distinguish the material points inside a body (block) and the material points outside this body (block)?

Thanks very much!

**Comment by djlittl** [comment]
Peridigm does not currently have the ability to do this, but you could modify the contact model to eliminate contact between two nodes that are in the same block.  You can access the Block_Id field within the contact model (not sure I have the name exactly right, it might be Block_ID, or similar).  When calculating the contact force between two nodes, you can just set the force to zero if the nodes have the same block_id.  This will not be great in terms of performance, because the contact search operation will still spend time searching for potential contact interactions between all nodes in the simulation, but this approach should give you the physics you’re looking for.

Dave

On Aug 8, 2019, at 10:29 AM, rbh007720 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

I am wondering how to enable the contact model between contacting bodies only, that is, there is no contact force within each body. So that I can model the bodies using correspondence material models, and the interactions between them are specified by the contact model, while there is no self-contact within them. How can I distinguish the material points inside a body (block) and the material points outside this body (block)?

Thanks very much!
