### ISSUE TITLE
problem with make test

### ISSUE THREAD

**Issue by Kai0136** [peridigm/peridigm#105]
HI Im trying to build peridynamic v1.5 on ubuntu 16.04
error when make test
97% tests passed, 5 tests failed out of 198

Total Test time (real) = 248.45 sec

The following tests FAILED:
	165 - Compression_2x1x1_np1 (Failed)
	166 - Compression_2x1x1_np2 (Failed)
	167 - Compression_3x1x1_np1 (Failed)
	168 - Compression_3x1x1_np2 (Failed)
	169 - Compression_3x1x1_np3 (Failed)
but i cant find the log file in the  test/regression, seems there's only compression 3x2x2

**Comment by maxincrease** [comment]
Hi! Could you tell me please which versions of the OpenMPI, Boost, HDF5, NetCDF and Trilinos do you use? Also, please, tell me the versions of all three compilers (fortran, c, c++). 
I just also have on ubuntu 16.04 a similar problem as you do now. 
Thanks!

**Comment by Kai0136** [comment]
Hi max 
well i have openmpi 2.0.1
                  boost 1_71_0
                  hdf5-1.8.15
                  netcdf-c-4.7.1
                  trilinos-12-10
                  gcc 5.4

**Comment by rahavvenk** [comment]
@Kai0136 You should find the log file under test/verification.

**Comment by Kai0136** [comment]
@rahavvenk  yeah, but i just cant find the log file of  165 - Compression_2x1x1_np1
166 - Compression_2x1x1_np2
167 - Compression_3x1x1_np1
168 - Compression_3x1x1_np2
169 - Compression_3x1x1_np3
i even cant find the fold named compression2x1x1or 3x1x1
and i have found  compression 3x2x2, and there are some errors in it:
exodiff: ERROR: .. Number of nodesets doesn't agree...
exodiff: ERROR: .. Nodeset id 1 exists in first file but not the second.
exodiff: ERROR: .. Nodeset id 2 exists in first file but not the second.
exodiff: ERROR: .. Nodeset id 3 exists in first file but not the second.
exodiff: ERROR: .. Nodeset id 4 exists in first file but not the second.
....
In my limited knowledge of installation of the linux source file, it seems nothing related with the building of peridigm? I dont know.

**Comment by Kai0136** [comment]
is there anyone could help me what's the problem with my installation

**Comment by maxincrease** [comment]
First of all, thank you, you helped me very much - I've installed all packages the same version as you did (boost, trilinos and so on) on the same ubuntu 16.04 and I managed to install the peridigm (all the tests are passed). 

Do you install a current master version of peridigm from github repository? (I just didn't get what do you mean by peridynamic **v1.5**, there is only 1.4.1 or a master version, at least on github)

**Comment by Kai0136** [comment]
@maxincrease oh good! yeah! I downloaded master version from github, and I saw some other issue in github says that they downloaded v1.5, and there is only master and 1.4.x version in github, so i think that mater version maybe v1.5. 
I still don't understand why i cant build peri correctly. It seems just a small problem now.
Do I need to reinstall all the requirements for peridigm? Does ubuntu have uninstall procedure as windows? And which tutorial did you use to install the peridigm? 
Thank you very much to reply.

**Comment by maxincrease** [comment]
Did you install all the packages and peridigim (before testing) completely without errors? 

In order to uninstall a program in ubuntu I just delete the installation folder's content, which is specified in such command: **../configure --prefix=/home/max/local/netcdf-4.7.1/** (in this particular case I delete the content of the folder **netcdf-4.7.1**).

Concerning the tutorial: the main problem (at least for me) was to find the right combination of the compatible version of all the packages (opempi, boost, hdf5, netcdf, trilinos) and compilers (fortran, c, c++) - and it's you, who gave me this combination (I wonder where you found it). 

So, I succeeded in it with the following commands (complete installation):

#Bullding OpenMPI
wget https://download.open-mpi.org/release/open-mpi/v2.0/openmpi-2.0.1.tar.gz
tar -xf openmpi-2.0.1.tar.gz
cd openmpi-2.0.1
mkdir build && cd build
../configure --prefix=/home/max/local/openmpi-2.0.1 CC=gcc CXX=g++ FC=gfortran
make -j
make install
cd ../..

#Export path for the usage of the new compiler
export CC=/home/max/local/openmpi-2.0.1/bin/mpicc 
export CXX=/home/max/local/openmpi-2.0.1/bin/mpicxx
export CF=/home/max/local/openmpi-2.0.1/bin/mpif90 
export FC=/home/max/local/openmpi-2.0.1/bin/mpif90 
export F77=/home/max/local/openmpi-2.0.1/bin/mpif77
export LIBRARY_PATH=/home/max/local/openmpi-2.0.1/lib/:${LIBRARY_PATH}
export PATH=/home/max/local/openmpi-2.0.1/bin/:$PATH

#Bullding Boost
wget https://dl.bintray.com/boostorg/release/1.71.0/source/boost_1_71_0.tar.gz
tar -xf boost_1_71_0.tar.gz
cd boost_1_71_0
#(upon request): sudo apt-get install libboost-all-dev
#(upon request): sudo apt-get install libbz2-dev
echo "using mpi ;" >> user-config.jam
./bootstrap.sh --prefix=/home/max/local/boost-1.71.0 
./b2 --layout=tagged -j 4
./b2 install 
cd ../..

#Building HDF5
wget https://support.hdfgroup.org/ftp//HDF5/prev-releases/hdf5-1.8/hdf5-1.8.15/src/hdf5-1.8.15.tar
tar -xf hdf5-1.8.15.tar
cd hdf5-1.8.15
mkdir build && cd build
../configure --prefix=/home/max/local/hdf5-1.8.15/ --enable-parallel 
make -j 4
make test 
make install 
cd ../..

#Building NETCDF
wget https://github.com/Unidata/netcdf-c/archive/v4.7.1.tar.gz
tar -xf v4.7.1.tar.gz
cd netcdf-c-4.7.1
H5DIR=/home/max/local/hdf5-1.8.15/ 
export CPPFLAGS="-I${H5DIR}/include" 
export LDFLAGS=-L${H5DIR}/lib 
# Configure NetCDF 
mkdir build && cd build
#(upon request): sudo apt-get install m4 
../configure --prefix=/home/max/local/netcdf-4.7.1/  --disable-netcdf-4 --disable-dap --enable-parallel
make -j 4
make install
cd ../..

#Building Trilinos
wget https://github.com/trilinos/Trilinos/archive/trilinos-release-12-10-1.tar.gz
tar -xf trilinos-release-12-10-1.tar.gz
cd /home/max/Trilinos-trilinos-release-12-10-1
mkdir build && cd build
#(upon request): sudo apt install cmake
#(upon request): sudo apt install libblas-dev
#(upon request): sudo apt install liblapack-dev
#(upon request): sudo apt install libx11-dev
cmake \
-D CMAKE_INSTALL_PREFIX:PATH=/home/max/local/trilinos-release-12.10.1 \
-D CMAKE_CXX_FLAGS:STRING="-O2 -ansi -pedantic -ftrapv -Wall -Wno-long-long" \
-D CMAKE_BUILD_TYPE:STRING=RELEASE \
-D Boost_NO_SYSTEM_PATHS=ON \
-D TPL_ENABLE_MPI=ON \
-D CMAKE_CXX_COMPILER=/home/max/local/openmpi-2.0.1/bin/mpicxx \
-D CMAKE_C_COMPILER=/home/max/local/openmpi-2.0.1/bin/mpicc \
-D Trilinos_WARNINGS_AS_ERRORS_FLAGS:STRING="" \
-D Trilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
-D Trilinos_ENABLE_Teuchos:BOOL=ON \
-D Trilinos_ENABLE_Shards:BOOL=ON \
-D Trilinos_ENABLE_Sacado:BOOL=ON \
-D Trilinos_ENABLE_Epetra:BOOL=ON \
-D Trilinos_ENABLE_EpetraExt:BOOL=ON \
-D Trilinos_ENABLE_Ifpack:BOOL=ON \
-D Trilinos_ENABLE_AztecOO:BOOL=ON \
-D Trilinos_ENABLE_Amesos:BOOL=ON \
-D Trilinos_ENABLE_Anasazi:BOOL=ON \
-D Trilinos_ENABLE_Belos:BOOL=ON \
-D Trilinos_ENABLE_ML:BOOL=ON \
-D Trilinos_ENABLE_Phalanx:BOOL=ON \
-D Trilinos_ENABLE_Intrepid:BOOL=ON \
-D Trilinos_ENABLE_NOX:BOOL=ON \
-D Trilinos_ENABLE_Stratimikos:BOOL=ON \
-D Trilinos_ENABLE_Thyra:BOOL=ON \
-D Trilinos_ENABLE_Rythmos:BOOL=ON \
-D Trilinos_ENABLE_MOOCHO:BOOL=ON \
-D Trilinos_ENABLE_TriKota:BOOL=OFF \
-D Trilinos_ENABLE_Stokhos:BOOL=ON \
-D Trilinos_ENABLE_Zoltan:BOOL=ON \
-D Trilinos_ENABLE_Piro:BOOL=ON \
-D Trilinos_ENABLE_Teko:BOOL=ON \
-D Trilinos_ENABLE_SEACASIoss:BOOL=ON \
-D Trilinos_ENABLE_SEACAS:BOOL=ON \
-D Trilinos_ENABLE_SEACASBlot:BOOL=ON \
-D Trilinos_ENABLE_Pamgen:BOOL=ON \
-D Trilinos_ENABLE_EXAMPLES:BOOL=OFF \
-D Trilinos_ENABLE_TESTS:BOOL=ON \
-D TPL_ENABLE_Matio=OFF \
-D TPL_ENABLE_HDF5:BOOL=ON \
-D HDF5_INCLUDE_DIRS:PATH="/home/max/local/hdf5-1.8.15/include" \
-D HDF5_LIBRARY_DIRS:PATH="/home/max/local/hdf5-1.8.15/lib" \
-D TPL_ENABLE_Netcdf:BOOL=ON \
-D Netcdf_INCLUDE_DIRS:PATH="/home/max/local/netcdf-4.7.1/include" \
-D Netcdf_LIBRARY_DIRS:PATH="/home/max/local/netcdf-4.7.1/lib" \
-D TPL_ENABLE_MPI:BOOL=ON \
-D TPL_ENABLE_BLAS:BOOL=ON \
-D TPL_ENABLE_LAPACK:BOOL=ON \
-D TPL_ENABLE_Boost:BOOL=ON \
-D Boost_INCLUDE_DIRS:PATH="/home/max/local/boost-1.71.0/include" \
-D Boost_LIBRARY_DIRS:PATH="/home/max/local/boost-1.71.0/lib" \
-D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
-D Trilinos_VERBOSE_CONFIGURE:BOOL=OFF \
-D Trilinos_ENABLE_TESTS=OFF \
/home/max/Trilinos-trilinos-release-12-10-1
make -j 4
make install
cd ../..

#Building Peridigm
#download peridigm and put it in the peridigm-master folder
cd peridigm-master
mkdir build && cd build
cmake \
-D CMAKE_BUILD_TYPE:STRING=Release \
-D Boost_NO_SYSTEM_PATHS=ON \
-D Trilinos_DIR:PATH=/home/max/local/trilinos-release-12.10.1/lib/cmake/Trilinos/ \
-D CMAKE_CXX_COMPILER=/home/max/local/openmpi-2.0.1/bin/mpicxx \
-D CMAKE_C_COMPILER=/home/max/local/openmpi-2.0.1/bin/mpicc \
-D BOOST_ROOT=/home/max/local/boost-1.71.0 \
-D CMAKE_CXX_FLAGS:STRING="-O2 -Wall -ansi -pedantic -Wno-long-long -ftrapv -Wno-deprecated -std=gnu++11 " \
..
make -j 4
make test

**Comment by Kai0136** [comment]
@maxincrease Thanks for reply. 
I reinstall ubuntu and build peridigm from scratch. 
When I was building hdf5, but the make test goes wrong, i wonder if there is something wrong with openmpi complier path I set. I just coppied the path to the bashrc file directly, saved and reboot the system. Did I do something wrong?

**Comment by maxincrease** [comment]
Could you send the error messages?

**Comment by Kai0136** [comment]
@maxincrease 
mpiexec has exited due to process rank 0 with PID 6032 on
node will exiting improperly. There are three reasons this could occur:

1. this process did not call "init" before exiting, but others in
the job did. This can cause a job to hang indefinitely while it waits
for all processes to call "init". By rule, if one process calls "init",
then ALL processes must call "init" prior to termination.

2. this process called "init", but exited without calling "finalize".
By rule, all processes that call "init" MUST call "finalize" prior to
exiting or it will be considered an "abnormal termination"

3. this process called "MPI_Abort" or "orte_abort" and the mca parameter
orte_create_session_dirs is set to false. In this case, the run-time cannot
detect that the abort call was an abnormal termination. Hence, the only
error message you will receive is this one.

This may have caused other processes in the application to be
terminated by signals sent by mpiexec (as reported here).

You can avoid this message by specifying -quiet on the mpiexec command line.

--------------------------------------------------------------------------
Command exited with non-zero status 1
0.29user 0.23system 0:00.24elapsed 213%CPU (0avgtext+0avgdata 16172maxresident)k
0inputs+5568outputs (22major+21793minor)pagefaults 0swaps
Makefile:1296: recipe for target 't_pflush1.chkexe_' failed
make[4]: *** [t_pflush1.chkexe_] Error 1
make[4]: Leaving directory '/home/will/download/hdf5-1.8.15/build/testpar'
Makefile:1371: recipe for target 'build-check-p' failed
make[3]: *** [build-check-p] Error 1
make[3]: Leaving directory '/home/will/download/hdf5-1.8.15/build/testpar'
Makefile:1276: recipe for target 'test' failed
make[2]: *** [test] Error 2
make[2]: Leaving directory '/home/will/download/hdf5-1.8.15/build/testpar'
Makefile:1079: recipe for target 'check-am' failed
make[1]: *** [check-am] Error 2
make[1]: Leaving directory '/home/will/download/hdf5-1.8.15/build/testpar'
Makefile:576: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1
Is this the error message?

**Comment by maxincrease** [comment]
Did you export the paths for the usage of the OpenMPI compiler (just by specifying in the terminal "export CC=...,export CXX=...," and so on (I sent you it in the instruction)), when you launched a terminal before building HDF5?

**Comment by Kai0136** [comment]
I just copy the complier path to the bashrc file 
export CC=/home/will/local/openmpi-2.0.1/bin/mpicc
export CXX=/home/will/local/openmpi-2.0.1/bin/mpicxx
export CF=/home/will/local/openmpi-2.0.1/bin/mpif90
export FC=/home/will/local/openmpi-2.0.1/bin/mpif90
export F77=/home/will/local/openmpi-2.0.1/bin/mpif77
export LIBRARY_PATH=/home/will/local/openmpi-2.0.1/lib/:${LIBRARY_PATH}
export PATH=/home/will/local/openmpi-2.0.1/bin/:$PATH
I simply open the bashrc file  and copy the path above and saved.
Is it wrong? Should I just put the path in the command window and enter?

**Comment by Kai0136** [comment]
@maxincrease 
I ran a test for mpi and it seems passed.
will@will:~/文档$ mpicxx test.cpp -o test
will@will:~/文档$ mpirun -n 4 ./test
Hello world. I'm the process 0, we are 4 process in total
Hello world. I'm the process 1, we are 4 process in total
Hello world. I'm the process 2, we are 4 process in total
Hello world. I'm the process 3, we are 4 process in total

**Comment by maxincrease** [comment]
By the way, did you install OpenMPI successfully without errors and you configured in this way "../configure --prefix=/home/will/local/openmpi-2.0.1 CC=gcc CXX=g++ FC=gfortran"?

**Comment by Kai0136** [comment]
@maxincrease  It seemed successful, and I just built hdf5 and netcdf without errors.
I deleted the old hdf5 fold and unzipped it again and it seems successful in make test.
Now I'm trying to build trilinos.

**Comment by Kai0136** [comment]
when configuring peridigm, though its done, some projects weren't used.
CMake Warning:
  Manually-specified variables were not used by the project:

    BOOST_ROOT
    Boost_NO_SYSTEM_PATHS
Is that means cmake doesn't use boost I built but the one in system?

**Comment by djlittl** [comment]
Peridigm no longer requires boost.  You can safely ignore this cmake warning.

Dave


---
Sent from Workspace ONE Boxer<https://whatisworkspaceone.com/boxer>

On October 15, 2019 at 8:50:11 PM MDT, Kai0136 <notifications@github.com> wrote:

when configuring peridigm, though its done, some projects weren't used.
CMake Warning:
Manually-specified variables were not used by the project:

BOOST_ROOT
Boost_NO_SYSTEM_PATHS


Is that means cmake doesn't use boost I built but the one in system?

**Comment by Kai0136** [comment]
yeah I saw the direction in github.
I also find boost in the trilinos cmake command.
So I still need to build boost for trilinos or just delete those boost path commands in trilinos cmake file?

**Comment by djlittl** [comment]
I’m pretty sure that Trilinos only requires the boost headers.  So you need to have boost, but you do not have to build boost.  The libraries are not needed, just the header files, which are there without building.

It’s possible that boost might be optional for Trilinos, in which case you don’t need it at all.  Sorry I don’t know the specifics on that.




On October 15, 2019 at 9:04:16 PM MDT, Kai0136 <notifications@github.com> wrote:

yeah I saw the direction in github.
I also find boost in the trilinos cmake command.
So I still need to build boost for trilinos or just delete those boost path commands in trilinos cmake file?

**Comment by Kai0136** [comment]
I built peridigm successfully. But .peridigm file is no longer supported. 
Should I build trilinos and peridigm again with yaml or just trilinos?

**Comment by djlittl** [comment]
You could either use the .xml format, which is still supported, or use the .yaml format.  In the case of yaml, you need to download and build yaml, then rebuild trilinos with the yaml flags turned on (and pointing to the yaml you just built).  You'll need to rebuild peridigm as well, so that it properly recognizes yaml within trilinos.  In my experience, building yaml and rebuilding trilinos is straightforward.

**Comment by Kai0136** [comment]
@djlittl I rebuilt trilinos with yaml flag. when I test peridigm,compression  3x1x1 failed again like I built with yaml at the first time. So there is something  wrong  with the procedure building with yaml. When I build trilinos without yaml, peridigm make test all passed.

**Comment by maxincrease** [comment]
@Kai0136 Just try to delete already used peridigm-master folder, download a new one from the repository and build peridigm there again considering all hints, which are mentioned above. 

It probably sounds redicilous, but it helped me solve my problem, when half of the random tests were failed. Probably it will help you as well.

**Comment by maxincrease** [comment]
@Kai0136 Now **I have absolutely the same problem** as you do: "when I test peridigm,compression 3x1x1 **failed** again like I built **with yaml** at the first time. When I build trilinos **without yaml**, peridigm make test **all passed**." And it fails absolutely in the same tests: 

165 - Compression_2x1x1_np1 (Failed)
166 - Compression_2x1x1_np2 (Failed)
167 - Compression_3x1x1_np1 (Failed)
168 - Compression_3x1x1_np2 (Failed)
169 - Compression_3x1x1_np3 (Failed)

Hope dear David Littlewood could help us)

In all cases the error in log-files are like this:

-- Peridigm
-- version 1.5.0 (Dev)

MPI initialized on 2 processors.

/home/max/pnf/trilinos-release-12.10-1-c/include/Teuchos_any.hpp:273:

Throw number = 1

Throw test that evaluated to true: operand.type() != typeid(ValueType)

/home/max/pnf/trilinos-release-12.10-1-c/include/Teuchos_any.hpp:273:

Throw number = 1

Throw test that evaluated to true: operand.type() != typeid(ValueType)

any_cast<string>(operand): Error, cast to type any::holder<string> failed since the actual underlying type is 'Teuchos::any::holder<int>!
any_cast<string>(operand): Error, cast to type any::holder<string> failed since the actual underlying type is 'Teuchos::any::holder<int>!
Wallclock Time (seconds):
                     Min            Max            Ave
  Total           0.0089          0.012          0.011

-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[13544,1],1]
  Exit code:    10
--------------------------------------------------------------------------
epu --  E Pluribus Unum
	(Out of Many One -- see http://www.greatseal.com/mottoes/unum.html)
	ExodusII Parallel Unification Program
	(Version: 4.17) Modified: 2016/04/13
Cannot open file './Compression_2x1x1.e.2.0'
ERROR: (EPU) Problem initializing input and/or output files.

   *****************************************************************
              EXODIFF	(Version: 2.85) Modified: 2016-08-08
              Authors:  Richard Drake, rrdrake@sandia.gov           
                        Greg Sjaardema, gdsjaar@sandia.gov          
              Run on    2019/10/19   20:44:34 CEST
   *****************************************************************

**Comment by Kai0136** [comment]
@maxincrease Actually, the first build with no yaml is successful, but .peridigm is no longer supported. so yaml is built, which lead to peridigm test failure.  And the log in test file of compression looks strange.

**Comment by Coooooco** [comment]
Dear all,
Did you all solve this "make test" failure? The very same problem happend to me as well, but I'm Ubuntu 18.04,the version of others are the same.
Thanks a lot.
Looking for your replies.
Coco

**Comment by Kai0136** [comment]
Not yet. Im going to edit the nosb pd code myself....

**Comment by Coooooco** [comment]
So sorry to hear that…maybe I should think about editing the pd code by self too…Wish all of us good luck…

**Comment by Kai0136** [comment]
Thank you, Co!

**Comment by maxincrease** [comment]
In this particular case there is a feeling, that those failed tests don't affect the functionality of Peridigm (it fails only with yaml-configuration and there is an issue something like " .. Number of nodesets doesn't agree..." - probably, it's only a matter of those particular test). 

Of cause, it's better to clear up what is wrong and solve it, but anyway you already built this program and you can use it for your simulations. Although you have to realize, that you take the responsibility for obtained results and you should ensure that these results agree with your expectations.
