### ISSUE TITLE
collocation points, volume of points in peridigm

### ISSUE THREAD

**Issue by Annaovgu** [peridigm/peridigm#112]
Hallo, 

I am trying to make banchmarcs with 1-D, 2-D and 3-D modells: bar, plate and beam with tensile loading at the free end.
The problem is, that I get the result, that compares correct with analytical only in case of 3-D model. In 1-D and 2-D case I get 6-fold..10-fold deviation.

For load i choose fiction layer and convert pressure in applied body force density for peridigm. For discretisation I generate text-file and somewhere here I think can be a mistake. I didn't find detailed information about what is the peridynamic collocation point and how can I compute the volume of this point, is it like cube or sphere? 

I have chosen to compute the volume like a cube and got the correct result just for 3-D, as I said. Maybe you can tell me what my mistake is? The way I count the volume or something else? 

Thank you in advance
Anna

**Comment by avvasen** [comment]
Anna, 

Peridigm is a 3-D code so it is not a surprise that you are not getting correct results for 1-D and 2-D models. What you need to do is to create alternative quasi 1-D and quasi 2-D models so that your bar, plate, and beam would have dimensions of at least a few horizons in all directions.   

-Alex
