### ISSUE TITLE
Memory usage increases dramatically with number of processors

### ISSUE THREAD

**Issue by masoudbehzadinasab** [peridigm/peridigm#12]
Dear Dr. Littlewood, 

Remember my problem with running Peridigm on the supercomputer? I found a new tool on TACC called REMORA (REsource MOnitoring for Remote Applications), which can be used to monitor Memory, CPU utilization, IO usage and so on. My problem turned out to be a lack of memory when I increase the number of processors per node for a problem size large enough. The memory available on a node from the cluster is 32 GB and the processors keep initializing the blocks until there is no memory available. Then the error occurs. It happens when the following line is being processed (line 456 in Peridigm.cpp).

<img src='http://s29.postimg.org/9dqj6xb7b/error_Peridigm_cpp.png' />

For example, for a mesh with ~230,000 PD nodes and ~7,700 Node Sets, the detailed memory usages for different number of processors as function of time are shown in the following images.

1 PRC:
<img src='http://s29.postimg.org/66xvgbz07/1_PRC.png' />

8 PRC:
<img src='http://s8.postimg.org/ixmoqgqol/8_PRC.png' />

16 PRC:
<img src='http://s9.postimg.org/zbocz6sv3/16_PRC.png' />

For this case, using 1 or 8 processors is just fine to run the code. But when I move to 16 processors, memory is not enough to handle it. The above image for 16 PRC show the complete output of REMORA, but for 1 and 8 PRCs, I show only 1 in ~10 time steps of output to make it more readable. Peridigm was run for 1 hour for the 1 PRC and 8 PRC cases. For the 16 PRC case, the error appeared after ~15 minutes of execution. 
**Conclusion from the images: The free memory out of the total of 27.5 GB, for 1 PRC: 24.5 GB, for 8 PRC: 10.7 GB, and for 16 PRC is nothing. How do you justify that??? Do you think high number of node sets caused this problem or there is something else going on?**

I am not clear what that line in Peridigm.cpp exactly does. As I have understood from debugging that part of the code, all the processors try to initialize all the blocks and assign some memory to them once by their own.  Shouldn't something else happens like only the processor rank 0 initialize the blocks? I have just been using Peridigm for a few months. So please correct me if I'm wrong. 

I know you mentioned that Peridigm is not really designed for high number of blocks, and I remember @johntfoster discussed it why we need that in our simulations. So I was wondering if we can solve the issue somehow. Otherwise, I will have to limit the number of processors I use, which technically means I won't be able to simulate larger problems that I am actually interested in. 

Thank you again for your time. Please let me know of your thoughts.

Masoud

**Comment by djlittl** [comment]
Masoud,

Glad you were able to figure this out.

A few comments:

The block initialization routine allocates memory.  So it makes sense that if you’re going to run out of memory, this might be the place where the code dies.

Broadly speaking, the memory required by Peridigm is a function of the number of bonds in the model.  Neighbor lists, including both bond lists and contact interaction lists, eat up the bulk of memory.  For this reason, the horizon and the contact search radius have a strong influence on the memory requirements.  It’s a good idea to double check those values for sanity.

When running on a cluster, you can generally decrease the memory requirement per node by increasing the number of partitions.  In other words, if you partition your mesh into 64 pieces and run on 4 nodes with 16 cores per node, and you run out of memory, you might try partitioning into 128 pieces and running on 8 nodes with 16 cores per node.  This decreases the number of bonds per node and will reduce the memory requirements on each node.

An important detail is that Peridigm ghosts nodes across both processor boundaries and block boundaries.  This is necessary because when it runs the material model for all the nodes in a block, it needs access to all the neighbors of all of those nodes.  The DataManager that gets passed into the constitutive model has all the nodes to be processed plus all the neighbors of those nodes, some of which may be in a different block or on a different processor.  This is one reason why running with a small number of nodes per block isn’t a great idea; you’ll end up with a lot of ghosts and this eats memory.

I highly doubt that the number of node sets matters.  It’s the neighbor lists that kill you in terms of memory usage, and after that it’s probably material state data.

With regard to processor 0 versus the other processors, each processor allocates memory for the nodes that it owns, plus ghosts.  So the initialization routine is run on every processor.  A well-balanced parallel simulation should give you approximately the same memory usage on each processor.

Your situation is inconvenient, but I don’t see how it limits the size of the simulation that you can run.  I suppose it’s conceivable that you could use the entire TACC supercomputer and thus be limited to simulations of a certain size, but I can’t imagine that you’re hitting this already.  Generally speaking, I believe the memory usage of Peridigm is reasonably well optimized.  Peridynamic simulations are inherent memory hogs relative to standard FEM simulations because of the need to store bond data (there are typically hundreds of bonds per node).

Here’s what I suggest you do:

1)  Check your horizon and contact search radius for sanity.

2)  Based on the data below, try to get a rough estimate of the number of bonds per node that you can support before running out of memory.  This is equivalent to figuring out the number of elements per node that you can support if you’re always running with a horizon that is 3x the node spacing.

3)  Partition your mesh so that the number of bonds per node is less that the number you approximated in 2).

4)  Check your cluster’s configuration options to see if you can set num_proc_per_node in your job submission script.  It almost certainly defaults to the number of nodes per processor (16).  If you set it a smaller number, then you will have more memory per processor.

One question for you:  Is Peridigm running out of memory right away, at the onset of the simulation, before any time steps are taken?  Or is it taking some number of steps and then running out of memory?

Hope this helps,
Dave

**Comment by masoudbehzadinasab** [comment]
Thank you for the information, Dr. Littlewood. 

Peridigm runs out of memory before any time step is taken. For the case I mentioned, it dies 15 minutes after the beginning of the program.

What you said makes a lot of sense. So for the same case, I tried running it once on 2 nodes with 32 PRC and another time on 4 nodes with 64 PRC. But I got the exact same result as I had with the case of 1 node and 16 PRC. 

REMORA output for 1 node and 16 PRCs:
<pre>
-- Peridigm                                                                     
-- version 1.5.0 (Dev)                                                          
                              
MPI initialized on 16 processors.                                               
                                                                                
[c558-702.stampede.tacc.utexas.edu:mpispawn_0][child_handler] MPI process (rank: 0, pid: 39547) terminated with signal 9 -> abort job
[c558-702.stampede.tacc.utexas.edu:mpispawn_0][readline] Unexpected End-Of-File on file descriptor 6. MPI process died?
[c558-702.stampede.tacc.utexas.edu:mpispawn_0][mtpmi_processops] Error while reading PMI socket. MPI process died?
[c558-702.stampede.tacc.utexas.edu:mpirun_rsh][process_mpispawn_connection] mpispawn_0 from node c558-702 aborted: MPI process error (1)
TACC: MPI job exited with code: 1                                               
                                                                                
TACC: Shutdown complete. Exiting.                                               
                                                                                
=============================== REMORA SUMMARY ===============================  
 Max Memory Used Per Node     : 39.76 GB                                        
*** REMORA: WARNING - Free memory per node close to zero:  -7.76 GB             
 Total Elapsed Time           : 0d 0h 15m 41s 85ms 
</pre>

REMORA output for 2 nodes and 32 PRCs:
<pre>
-- Peridigm                                                                     
-- version 1.5.0 (Dev)                                                          
                                                                                
MPI initialized on 32 processors.                                               
                                                                                
[c557-203.stampede.tacc.utexas.edu:mpispawn_0][child_handler] MPI process (rank: 0, pid: 89057) terminated with signal 9 -> abort job
[c557-203.stampede.tacc.utexas.edu:mpispawn_0][readline] Unexpected End-Of-File on file descriptor 17. MPI process died?
[c557-203.stampede.tacc.utexas.edu:mpispawn_0][mtpmi_processops] Error while reading PMI socket. MPI process died?
[c557-203.stampede.tacc.utexas.edu:mpirun_rsh][process_mpispawn_connection] mpispawn_0 from node c557-203 aborted: MPI process error (1)
[c557-901.stampede.tacc.utexas.edu:mpispawn_1][read_size] Unexpected End-Of-File on file descriptor 21. MPI process died?
[c557-901.stampede.tacc.utexas.edu:mpispawn_1][read_size] Unexpected End-Of-File on file descriptor 21. MPI process died?
[c557-901.stampede.tacc.utexas.edu:mpispawn_1][handle_mt_peer] Error while reading PMI socket. MPI process died?
TACC: MPI job exited with code: 1                                               
                                                                                
TACC: Shutdown complete. Exiting.                                               
                                                                                
=============================== REMORA SUMMARY ===============================  
 Max Memory Used Per Node     : 39.78 GB                                        
*** REMORA: WARNING - Free memory per node close to zero:  -7.78 GB             
 Total Elapsed Time           : 0d 0h 15m 14s 75ms   
</pre>

REMORA output for 4 nodes and 64 PRCs:
<pre>
-- Peridigm                                                                     
-- version 1.5.0 (Dev)                                                          
                                                                                
MPI initialized on 64 processors.                                               
                                                                                
[c557-203.stampede.tacc.utexas.edu:mpispawn_1][readline] Unexpected End-Of-File on file descriptor 9. MPI process died?
[c557-203.stampede.tacc.utexas.edu:mpispawn_1][mtpmi_processops] Error while reading PMI socket. MPI process died?
[c557-203.stampede.tacc.utexas.edu:mpispawn_1][child_handler] MPI process (rank: 16, pid: 107546) terminated with signal 9 -> abort job
[c557-201.stampede.tacc.utexas.edu:mpirun_rsh][process_mpispawn_connection] mpispawn_1 from node c557-203 aborted: Error while reading a PMI socket (4)
[c557-201.stampede.tacc.utexas.edu:mpispawn_0][read_size] Unexpected End-Of-File on file descriptor 22. MPI process died?
[c557-201.stampede.tacc.utexas.edu:mpispawn_0][read_size] Unexpected End-Of-File on file descriptor 22. MPI process died?
[c557-201.stampede.tacc.utexas.edu:mpispawn_0][handle_mt_peer] Error while reading PMI socket. MPI process died?
[c558-501.stampede.tacc.utexas.edu:mpispawn_2][read_size] Unexpected End-Of-File on file descriptor 21. MPI process died?
[c558-501.stampede.tacc.utexas.edu:mpispawn_2][read_size] Unexpected End-Of-File on file descriptor 21. MPI process died?
[c558-501.stampede.tacc.utexas.edu:mpispawn_2][handle_mt_peer] Error while reading PMI socket. MPI process died?
[c558-502.stampede.tacc.utexas.edu:mpispawn_3][read_size] Unexpected End-Of-File on file descriptor 21. MPI process died?
[c558-502.stampede.tacc.utexas.edu:mpispawn_3][read_size] Unexpected End-Of-File on file descriptor 21. MPI process died?
[c558-502.stampede.tacc.utexas.edu:mpispawn_3][handle_mt_peer] Error while reading PMI socket. MPI process died?
TACC: MPI job exited with code: 1                                               
                                                                                
TACC: Shutdown complete. Exiting.                                               
                                                                                
=============================== REMORA SUMMARY ===============================  
 Max Memory Used Per Node     : 39.97 GB                                        
*** REMORA: WARNING - Free memory per node close to zero:  -7.97 GB             
 Total Elapsed Time           : 0d 0h 15m 43s 229ms
</pre>

With your suggestion, I checked the horizon and the search radius. I was able to reduce them a bit. In my simulation, node spacing is about 0.00317, so I modified the horizon to 0.00955 (it was 0.012 before). I also set the search radius to 0.015 (it was 0.0175 before). Then I ran the code. But it made no difference.
<pre>
-- Peridigm                                                                     
-- version 1.5.0 (Dev)                                                          
                                                                                
MPI initialized on 16 processors.                                               
                                                                                
[c557-504.stampede.tacc.utexas.edu:mpispawn_0][child_handler] MPI process (rank: 0, pid: 315) terminated with signal 9 -> abort job
[c557-504.stampede.tacc.utexas.edu:mpispawn_0][readline] Unexpected End-Of-File on file descriptor 18. MPI process died?
[c557-504.stampede.tacc.utexas.edu:mpispawn_0][mtpmi_processops] Error while reading PMI socket. MPI process died?
[c557-504.stampede.tacc.utexas.edu:mpirun_rsh][process_mpispawn_connection] mpispawn_0 from node c557-504 aborted: MPI process error (1)
TACC: MPI job exited with code: 1                                               
                                                                                
TACC: Shutdown complete. Exiting.                                               
                                                                                
=============================== REMORA SUMMARY ===============================  
 Max Memory Used Per Node     : 39.74 GB                                        
*** REMORA: WARNING - Free memory per node close to zero:  -7.74 GB             
 Total Elapsed Time           : 0d 0h 15m 29s 873ms 
</pre>

I am not sure why it is still happening. It looks like the partitioning has not divided the mesh into smaller portions among the computing nodes, and each of the processors is still trying to initialize blocks for the same number as before.

The limitation I was talking about is because in my actual size simulation, if I use more than 3 cores from a node, then the error comes up. And like I mentioned in my example above, it doesn't matter if I use 1 node and 4 cores or 10 nodes and 40 cores (4 from each), it will still crash. 

By the way, I was using a text file as the discretization file, so I was not partitioning it manually and Peridigm was supposed to take care of that. However, just to make sure, I tried your text_to_genesis.py script and converted my text files to genesis format and then used decomp to partition it into 32. Then I ran the code on 2 nodes and 32 cores. I got the exact same result --> Memory Error.

Any new ideas? 

Thanks again for your help.
Masoud

**Comment by masoudbehzadinasab** [comment]
Dear All, 

It's been a while, but revisiting the issue by Dr. Foster and I, we were able to find a solution to the problem. As Dr. Littlewood mentioned earlier, Peridigm is not really designed for too large number of blocks. Redistributing the PD nodes in a way using much smaller number of blocks reduced the memory usage and run time by orders of magnitude. I should also mention that, using too many compute classes was also a problem. Previously, we were using the Nearest PD node feature of the compute classes, to trace each particle grain center properties (about 20,000 compute classes in one of the base cases). Comping up with an alternate solution and turning off all of those compute classes resulted in a big reduction in memory usage and time consumption. 

Moreover, that parallelization issue was also related to the number of blocks. Running the simulations now on multiple computing nodes has no problem. 

Dr. Littlewood: Thanks so much for helping me understanding Peridigm better and finding a solution.

Regards,
Masoud
