### ISSUE TITLE
Unable to use text_to_genesis.py

### ISSUE THREAD

**Issue by xander9595** [peridigm/peridigm#132]
Hi, I am tring to use text_to_genesis.py to convert my .txt file.

Form the message below, It seems like I only has the libexodus.a in the local/trilinos-12.0.1/lib/. How can I get the libexodus.so? 

diehl@ubuntu:~/material$ python text_to_genesis.py
Traceback (most recent call last):
  File "text_to_genesis.py", line 65, in <module>
    import exodus
  File "/home/diehl/trilinos-release-12-0-1/build/packages/seacas/scripts/exodus.py", line 110, in <module>
    EXODUS_LIB = cdll.LoadLibrary(EXODUS_SO)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/diehl/local/trilinos-12.0.1/lib/libexodus.so: cannot open shared object file: No such file or directory

**Comment by jritta** [comment]
If you want to use shared libraries of Trilinos you must compile it with the flag -D BUILD_SHARED_LIBS=ON in cmake.
Hope that helps!
Best, Jonas

**Comment by oldninja** [comment]
As @jritta mentioned, you will need to recompile with shared libraries on. Make sure your LAPACK/BLAS are also shared libraries - otherwise you will have some issues.

**Comment by xander9595** [comment]
> If you want to use shared libraries of Trilinos you must compile it with the flag -D BUILD_SHARED_LIBS=ON in cmake.
> Hope that helps!
> Best, Jonas

It's very helpful. Thank you!

**Comment by berraw** [comment]
Hi Everyone,

I would like to ask another question on this subject. I am trying to convert a txt file (examples/wave_in_bar) to the g file. And I receive an error message as follows.

**./text_to_genesis.py wave_in_bar.txt node_set_1.txt node_set_2.txt**

---- Text to Genesis

Discretization file:
 wave_in_bar.txt

Node set files:
 node_set_1.txt
 node_set_2.txt

Read 10000 nodes and 1 block from wave_in_bar.txt
Read 9400 node ids from node_set_1.txt
Read 600 node ids from node_set_2.txt

You are using exodus.py v 1.20.8 (seacas-py3), a python wrapper of some of the exodus library.

Copyright (c) 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021 National Technology &
Engineering Solutions of Sandia, LLC (NTESS).  Under the terms of
Contract DE-NA0003525 with NTESS, the U.S. Government retains certain
rights in this software.

Opening exodus file: wave_in_bar.g
Traceback (most recent call last):
  File "./text_to_genesis.py", line 255, in <module>
    main()
  File "./text_to_genesis.py", line 244, in main
    write_exodus_file(textFileName, X, Y, Z, vol, blocks, nodeSets)
  File "./text_to_genesis.py", line 170, in write_exodus_file
    exodusFile.put_concat_elem_blk(exodusBlockIds,
  File "/home/jnuos/peri/trilinos/lib/exodus3.py", line 2574, in put_concat_elem_blk
    self.__ex_put_concat_elem_blk(
  File "/home/jnuos/peri/trilinos/lib/exodus3.py", line 4918, in __ex_put_concat_elem_blk
    elem_type[:] = elemType
TypeError: bytes or integer address expected instead of str instance

**Comment by jritta** [comment]
This seems to be a bug in `exodus3.py`. Executing it as `python2 text_to_genesis.py wave_in_bar.txt node_set_1.txt node_set_2.txt` should solve this issue (`exodus2.py` is used instead of `exodus3.py`)

Best
Jonas

**Comment by berraw** [comment]
Thank you, I really appreciate it. It works ))
