### ISSUE TITLE
Heat Flux with Peridigm

### ISSUE THREAD

**Issue by Juliendu33** [peridigm/peridigm#18]
Hello, 

Will I have wanted to know if it were possible to model the propagation of a heat flux on a plate (for example) with Peridigm? 
If so, it is possible to direct this flow according to one of the axes of the plate (I think that should not be difficult). 

Still thank you very much by advance.
Cordially
Julien

**Comment by djlittl** [comment]
Peridigm is not currently capable of modeling heat conduction.  You can, however, prescribe a temperature over the domain as a function of position and time.  Some of the material models can then incorporate thermal strains based on this temperature field.

**Comment by MDBrothers** [comment]
Julien,

Much of the work for doing that has already been done; there is a poroelasticity model in Peridigm. It involves a diffusion model and couples fluid pressure to dilatation force in the elasticity model.

For a good conduction model, you would need to derive the correct constitutive constants for the diffusion model and you would need to create another material model for peridynamic thermoelasticity.

Alternatively you could forgo coupling.

**Comment by pietrodantuono** [comment]
Hello Julien,

I have implemented the peridynamic thermal problem in Peridigm (it is a parallel implementatiom, as Peridigm is), but since I did this job on an older version of the code (1.4.1), I am going to port my work on the github version during the next few weeks.

I also worked upon a proper explicit integrator to solve thermo-mechanical problems in which the domain is subjected to very high thermal loads, hence crack nucleation occurs.

The code provides good results (I posted a few a few videos on Youtube). Nonetheless, right now the thermo-mechanical problem is just wealky coupled, hence it is suitable for problem with low strain rates. But I just started working on strong coupling in order to be able to model, in the future, thermo-plasticity.
