### ISSUE TITLE
Uniform HEX mesh Vs Non-Uniform Hex Mesh

### ISSUE THREAD

**Issue by ppandit95** [peridigm/peridigm#181]
I am trying to make a geomerty in coreform cubit where I have non uniform HEX mesh instead of HEX mesh which failed as opposed to when I tried with uniform mesh.Any headers in this regard will prove beneficial.

**Comment by djlittl** [comment]
Are you saying that cubit failed to create the mesh, or are you saying that cubit did create the mesh but Peridigm failed to read it?

Nonuniform hex or tet meshes should be fine in Peridigm.  Creation of hex meshes in general (in cubit or otherwise) is not guaranteed to work.  It’s an unsolved problem in meshing.  Creation of a tet mesh is basically guaranteed to work, although reading a tet mesh into Peridigm is generally less pleasing than a hex mesh just because the hex mesh results in a smoother-looking meshless discretization (especially near the surfaces).  But mathematically speaking, reading either a hex or tet mesh into Peridigm is totally valid.

**Comment by ppandit95** [comment]
At first I thought Peridigm failed to read the non uniform mesh but
eventually after some attempts I was able to run the non uniform mesh and
the issue originally was with the larger number of elements (approx 48 000)
which I was initially trying to run on single processor and the simulation
was failing so I tried to run the simulation in parallel which is working
perfectly .

Moreover,thanks @djlittle for  sharing insights about HEX meshes which I
didn't know before.

**Comment by ppandit95** [comment]
At first I thought Peridigm failed to read the non uniform mesh but
eventually after some attempts I was able to run the non uniform mesh and
the issue originally was with the larger number of elements (approx 48 000)
which I was initially trying to run on single processor and the simulation
was failing so I tried to run the simulation in parallel which is working
perfectly .

Moreover,thanks @djlittle for  sharing insights about HEX meshes which I
didn't know before.
