### ISSUE TITLE
Storing the ParameterList for a Generic Material Name

### ISSUE THREAD

**Issue by ppandit95** [peridigm/peridigm#225]
Dear Peridigm Community,

While working with multiple material model and using a customized material model, I have added 

Teuchos::ParameterList mymaterialparams = materialParams.sublist("My Material");

in core/Peridigm_Factory.cpp to take in certain parameters before-hand but the issue I am facing is that it will only take in the parameterlist corresponding to "My Material" entry in yaml file but for a customized yaml script I have "My Material_1" , "My Material_2" and so on up to 1000.So in this regard, I wish to get your help in order to get a material parameters corresponding to generic material name like "My Material_".

Many Thanks 
Pushkar

**Comment by oldninja** [comment]
Hi @ppandit95, I believe each of those materials would be treated as different materials within Peridigm, right? Or maybe I didn't understand the problem well.

**Comment by djlittl** [comment]
I'm a bit confused about what you're trying to do.  Are you using the same material model in all cases, but wanting to assign different material parameters?  For example, as in a polycrystal that uses the elastic material model for every grain but each grain has slightly different moduli?

**Comment by ppandit95** [comment]
@djlittl as you suspected I am trying to use same material model but assign varying properties to each block through various material entries in yaml file so I can take in a property for all material models in an array as opposed to single value in case of single material model .

**Comment by djlittl** [comment]
I think the only way you can do this without any code development is to have separate entries in the yaml file for each block in the discretization.  So, you'd have a discretization with 1000's of blocks and a separate material model and block entry for each in the yaml file.  You would presumably want to script this so you're not typing them in the yaml file by hand.  The yaml file would be unwieldy, but Peridigm shouldn't have a problem with it.  You may see a performance hit if you have thousands of blocks since data structures, etc., are managed internally by Peridigm on a block-by-block basis.

Another option would be to store the material properties on an exodus input mesh.  Then Peridigm could read the data and store it as a field variable.  The material model code could be modified to read material properties from this field.  This would take a bit of development work but would solve the problem of a huge yaml file and would probably give better performance because you wouldn't have a huge number of blocks.

If I were in your shoes, I would try option 1) and see just how painful it is before digging in to option 2).

**Comment by ppandit95** [comment]
First of all, thanks @djlittl for replying to this issue quickly.As you elaborated I have created a script to input geometry as a text file but the issue is that I am using a model which has been  created as a part of research but it requires an auxiliary field which takes in a value of Hardening Modulus to make computations and as a quick implementation I have made an arrangement in Peridigm_Factroy.cpp (passed on to the solver)to take in this value which will be used in Peridigm_Material.cpp to evolve the field over the course of simulation and it is working perfectly for a single material block but that creates an issue when multiple blocks are involved so I was hoping if I could know how different material blocks are taken by Peridigm(May be a reference to relevant code snippet from the source files would be just great).

Thanks in Advance

**Comment by djlittl** [comment]
I'll post two responses on this, the first to follow up on my initial idea above.

I think storing the material properties on a point-by-point basis on a mesh file and reading it into Peridigm using the Data_Loader functionality would work in your case.  In Peridigm, you'd only have to modify the material model code itself to read this new field variable and use those values for the force calculations.

There would be some pre-processing involved.  You'd want to use the text_to_genesis.py script that is in the Peridigm/scripts directory to convert your text file mesh to an exodus file.  Then you could write a python script using the exodus.py module to add a field to the exodus mesh for storing the material properties.  For an example, see the test

/Users/djlittl/Peridigm/peridigm/test/regression/Notched_Plate_Data_Loader

This test includes a script for adding a field to the exodus file, create_data_file.py.

**Comment by djlittl** [comment]
Second post, trying to answer your question about how blocks are handled.

This is a tough one, because I don't really understand how you have it working for a single material.  It sounds like you are intercepting the calls that create the material models in the first place and adding new values to the ParameterList, so that the materials have all the data you want in their constructors?  If this is what you are doing, why not just put the data in the input deck instead?  It's true that the input deck could get really long, but Peridigm should still be able to read it.  You would just need to modify the material model code to read the new entry in the parameter list.

The high-level answer to your question is that the discretization is divided up into blocks, where each block has a material model assigned to it (and possibly a damage model, etc.).  If I recall correctly, a material model is instantiated for each block at the beginning of the simulation, using the material factory class.  There are many places in the code where we loop over the blocks in the model.  For example, when evaluating the internal force, Peridigms goes through the blocks one at a time and then sums all the resulting pairwise forces.  You can see an example of these loops in Peridigm_ModelEvaluator.cpp.

**Comment by ppandit95** [comment]
Thanks @djlittl for elaborating on the structure of the program and how material model is instantiated and I have added a field Hardening Modulus in the input deck which I take at the time of making a peridigm_factory object in Peridigm_Main.cpp that is further passed on to executesolves() method from where Peridigm_modelEvaluator() class takes in this value as an argument to compute the relevent auxiliary field which evolves over time.Another suggestion to use Data Loader seems inadequate as I am not sure it can have fields that evolve over time .

Thanks
Pushkar

**Comment by ppandit95** [comment]
Thanks @djlittl and @oldninja for helping me out in this context as your suggestions were truly helpful and I managed to get the hardening modulus for each block in computation .

Regards
Pushkar
