### ISSUE TITLE
Restart Feature is Computationally Intensive

### ISSUE THREAD

**Issue by bdas123** [peridigm/peridigm#266]
Hello!

As stated in the title, the restart feature is an intensive operation. At my university, I only have 48 hours to perform a single run. Should I use the restart feature, I have little time to progress the simulation. 

Is there any way to make this less intensive? I'd be happy to code this up if someone could point me in the right direction.

**Comment by andrisfreimanis** [comment]
Hei,
a while ago I had a similar problem using the QS and nox solvers. I'm traveling now and can't access my laptop, so I'm writing this from memory. Maybe helps you implement something. If not, I'll check next week if I can share our code.

The step after reading restart is slow because it doesn't have the predictor values (velocity) from the last step. Write restart function actually writes velocity values to file, and readRestart reads them.

The issue was that solvers at step zero overwrite them with all zeros. You could implement an if statement that checks if this is step 0, then puts zeros in predictor if true, and velocity values if false.

Or implement a similar if statement, but have the user pass a parameter in yaml file under  solver e.g. "Use predictor from restart: true/false". Then have restart enabled and two or more chained solver in the input file. Parameter value would be false for the first solver, but true for the following solvers

Best
Andris Freimanis

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: Barun Das ***@***.***>
Sent: Wednesday, September 14, 2022, 14:38
To: peridigm/peridigm ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [peridigm/peridigm] Restart Feature is Computationally Intensive (Issue #266)


Hello!

As stated in the title, the restart feature is an intensive operation. At my university, I only have 48 hours to perform a single run. Should I use the restart feature, I have little time to progress the simulation.

Is there any way to make this less intensive? I'd be happy to code this up if someone could point me in the right direction.

**Comment by oldninja** [comment]
@andrisfreimanis I would be interested on waiting to see your implementation. Any plans to submit a PR?

**Comment by andrisfreimanis** [comment]
I can submit that code. but will wait after the #261 is merged.
