### ISSUE TITLE
CMake warning preventing Peridigm configuration

### ISSUE THREAD

**Issue by Jacob328** [peridigm/peridigm#295]
Hi!

I have been attempting to install Peridigm on my University's computer cluster and have encountered an error message that I can't seem to work through. The meat of the error message is as follows:

```
CMake Warning at /home/jacobow/TrilinosMake/TrilinosConfig.cmake:44 (message):
  TrilinosConfig.cmake has moved.  It now exists at a location under the
  installation prefix where the find_package command looks by default
  (<prefix>/lib/cmake/Trilinos).  This compatibility file exists at the old
  location (<prefix>/include) to present this message and load the file from
  its new location.

  The find_package() call that loaded this file did so because its cached
  result variable, Trilinos_DIR, is set to

    /home/jacobow/TrilinosMake

  I'm locally setting Trilinos_DIR to

    /home/jacobow/lib/cmake/Trilinos

  and loading TrilinosConfig.cmake from its new location.  One may suppress
  this warning by setting the above value in the cache.  However, the
  application needs modification permanently fix the issue.  The
  find_package() call that loaded this file may have the form

    find_package(Trilinos REQUIRED PATHS ${Trilinos_PATH}/include)

  Change it to the form

    set(CMAKE_PREFIX_PATH ${Trilinos_PATH} ${CMAKE_PREFIX_PATH})
    find_package(Trilinos REQUIRED)

  to find TrilinosConfig.cmake in its new location in future builds while
  still honoring the Trilinos_PATH option for this application.
Call Stack (most recent call first):
  CMakeLists.txt:50 (FIND_PACKAGE)


CMake Error at /home/jacobow/TrilinosMake/TrilinosConfig.cmake:66 (include):
  include could not find load file:

    /home/jacobow/lib/cmake/Trilinos/TrilinosConfig.cmake
Call Stack (most recent call first):
  CMakeLists.txt:50 (FIND_PACKAGE)
```

The univeresity's cluster already had a copy of Trilinos installed, but as it was not built with the NetCDF package, I rebuilt and installed my own version of Trilinos with all required libraries at the location /home/jacobow/TrilinosMake mentioned in the error message. 

The cmake command I'm using in attempt to begin the Peridigm installation process is:

```
rm -f CMakeCache.txt
rm -rf CMakeFiles/

cmake \
-D CMAKE_BUILD_TYPE:STRING=Release \
-D Trilinos_DIR:STRING=/home/jacobow/TrilinosMake/ \
-D CMAKE_C_COMPILER:STRING=$EBROOTOPENMPI/bin/mpicc \
-D CMAKE_CXX_COMPILER:STRING=$EBROOTOPENMPI/bin/mpicxx \
-D BOOST_ROOT=$EBROOTBOOST \
-D CMAKE_CXX_FLAGS:STRING="-O2 -Wall -std=c++11 -pedantic -Wno-long-long -ftrapv -Wno-deprecated" \
-D CMAKE_INSTALL_PREFIX="/home/jacobow/PeridigmMake" \
/home/jacobow/Downloads/Src/PeridigmMaster
```
where /home/jacobow/Downloads/Src/PeridigmMaster is the location of the downloaded Peridigm source code.

I would hugely appreciate any insight anyone may have!

**Comment by andrisfreimanis** [comment]
Dear Jacob,
as I understand CMake is looking for TrilinosConfig.cmake file. It should be in <trilinos base dir>/lib/cmake/Trilinos. I usually give the full path to that directory as in the line below.

      -D Trilinos_DIR:PATH=$SOFTWARE_DIR/trilinos/lib/cmake/Trilinos/ \

Best regards
Andris
________________________________
From: Jacob328 ***@***.***>
Sent: Monday, 16 January 2023 7.44
To: peridigm/peridigm ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [peridigm/peridigm] CMake warning preventing Peridigm configuration (Issue #295)


Hi!

I have been attempting to install Peridigm on my University's computer cluster and have encountered an error message that I can't seem to work through. The meat of the error message seems is as follows:

CMake Warning at /home/jacobow/TrilinosMake/TrilinosConfig.cmake:44 (message):
  TrilinosConfig.cmake has moved.  It now exists at a location under the
  installation prefix where the find_package command looks by default
  (<prefix>/lib/cmake/Trilinos).  This compatibility file exists at the old
  location (<prefix>/include) to present this message and load the file from
  its new location.

  The find_package() call that loaded this file did so because its cached
  result variable, Trilinos_DIR, is set to

    /home/jacobow/TrilinosMake

  I'm locally setting Trilinos_DIR to

    /home/jacobow/lib/cmake/Trilinos

  and loading TrilinosConfig.cmake from its new location.  One may suppress
  this warning by setting the above value in the cache.  However, the
  application needs modification permanently fix the issue.  The
  find_package() call that loaded this file may have the form

    find_package(Trilinos REQUIRED PATHS ${Trilinos_PATH}/include)

  Change it to the form

    set(CMAKE_PREFIX_PATH ${Trilinos_PATH} ${CMAKE_PREFIX_PATH})
    find_package(Trilinos REQUIRED)

  to find TrilinosConfig.cmake in its new location in future builds while
  still honoring the Trilinos_PATH option for this application.
Call Stack (most recent call first):
  CMakeLists.txt:50 (FIND_PACKAGE)


CMake Error at /home/jacobow/TrilinosMake/TrilinosConfig.cmake:66 (include):
  include could not find load file:

    /home/jacobow/lib/cmake/Trilinos/TrilinosConfig.cmake
Call Stack (most recent call first):
  CMakeLists.txt:50 (FIND_PACKAGE)


The univeresity's cluster already had a copy of Trilinos installed, but as it was not built with the NetCDF package, I rebuilt and installed my own version of Trilinos with all required libraries at the location /home/jacobow/TrilinosMake mentioned in the error message.

The cmake command I'm using in attempt to begin the Peridigm installation process is:

rm -f CMakeCache.txt
rm -rf CMakeFiles/

cmake \
-D CMAKE_BUILD_TYPE:STRING=Release \
-D Trilinos_DIR:STRING=/home/jacobow/TrilinosMake/ \
-D CMAKE_C_COMPILER:STRING=$EBROOTOPENMPI/bin/mpicc \
-D CMAKE_CXX_COMPILER:STRING=$EBROOTOPENMPI/bin/mpicxx \
-D BOOST_ROOT=$EBROOTBOOST \
-D CMAKE_CXX_FLAGS:STRING="-O2 -Wall -std=c++11 -pedantic -Wno-long-long -ftrapv -Wno-deprecated" \
-D CMAKE_INSTALL_PREFIX="/home/jacobow/PeridigmMake" \
/home/jacobow/Downloads/Src/PeridigmMaster


where /home/jacobow/Downloads/Src/PeridigmMaster is the location of the downloaded Peridigm source code.

I would hugely appreciate any insight anyone may have!

**Comment by Jacob328** [comment]
@andrisfreimanis thank you so much for helping to interpret that error message! The cmake command now runs to completion without printing errors, but the following warning now pops up:

```
CMake Warning at /home/jacobow/TrilinosMake/lib/cmake/Kokkos/KokkosConfig.cmake:190 (MESSAGE):
  The installed Kokkos configuration does not support CXX extensions.
  Forcing -DCMAKE_CXX_EXTENSIONS=Off
```
Ignoring the warning and attempting to run "make" resulted in fairly rapid failure that didn't seem to have any obvious error messages. Do you think the status update -DCMAKE_CXX_EXTENSIONS=OFF causes the failure when attempting to run "make"? If so, maybe I made a mistake somewhere in my Trilinos build...

**Comment by andrisfreimanis** [comment]
It's been a while since I compiled Peridigm, but that warning shouldn't be it.

Maybe you can run 'make > make.out'. It will write the output of make into a file make.out. if you post that file, could take a look.

Andris
________________________________

**Comment by Jacob328** [comment]
Running `make -j 32 > make.out 2>&1` gives me the following lengthy output. Thank you for offering to take a look at it!
[make.txt](https://github.com/peridigm/peridigm/files/10428312/make.txt)

**Comment by andrisfreimanis** [comment]
I see two things there.

(1) /home/jacobow/TrilinosMake/include/desul/atomics/Common.hpp:128:29: error: ‘conditional_t’ in namespace ‘std’ does not name a template type; did you mean ‘conditional’?

(2) /home/jacobow/TrilinosMake/include/desul/atomics/Compare_Exchange_GCC.hpp:60:1: note: ‘std::enable_if_t’ is only available from C++14 onwards

Did you have --std=c++14 in your CFLAGS when compiling trilinos and peridigm? If not, could try with that

Andris
________________________________

**Comment by Jacob328** [comment]
I don't think so! I'll try that. To be clear, you mean changing 
`-D CMAKE_CXX_FLAGS:STRING="-O2 -std=c++11..."` to `-D CMAKE_CXX_FLAGS:STRING="-O2 -std=c++14..."` within the cmake command arguments, correct?

**Comment by Jacob328** [comment]
Thanks so much again @andrisfreimanis 

Finally got everything to work!
