### ISSUE TITLE
How to set up contact interactions for different blocks

### ISSUE THREAD

**Issue by AimZhang** [peridigm/peridigm#297]
I am trying to do multiple balls impacting the substrate. How to set up the contact interactions between different ball blocks. It seems peridigm cannot check and implement the input deck information even when I specify the interaction of ball blocks. Here, I used the short-range force contact model. 
![Multiple balls impact system](https://user-images.githubusercontent.com/110468396/215534831-26b45336-2569-46d0-b1cd-89f6fc6b287d.png)

**Comment by djlittl** [comment]
As of today, I believe Peridigm can only handle contact between two blocks.  You can have multiple balls contacting the target by putting all the balls into the same block.  But the balls won't interact with each other, only with the target.

The input deck syntax probably implies that Peridigm can handle an arbitrary number of blocks for contact.  This is the long-term plan, but making it fully functional will require a significant programming effort.

**Comment by AimZhang** [comment]
Thank you very much. I tried to make all the balls as one block impacting the target. The jetting of the bottom two balls will have an influence on the movement of the other three balls, thus the calculation is aborted when the red ball (shown in the above picture) contacts the jetting. Could you please show me how to fix it? Thanks a lot again.

**Comment by djlittl** [comment]
I don't see why this would be the case.  Interactions between the red ball and any nodes in the other balls should be ignored (even if we wish they weren't).

Is there any possibility that there are bonds between the balls?  This might occur if the horizon is roughly the size of the balls, or larger.  I assume you would not want the balls to be bonded to each other, but this could happen by mistake if the horizon is large.  I ask because this could cause numerical problems for some material models if the balls get very close to each other.

Another possibility is that there are nodes that end up very close to each other and the resulting contact force is huge, causing the simulation to go haywire.  There is no foolproof way to avoid this for the short-range force contact model.  The only approach I'm aware of is to experiment with different (smaller) time steps or perhaps change the contact interaction distance or contact spring constant.

**Comment by AimZhang** [comment]
Thank you very much for your detailed explanation. I appreciate it. **Actually, I want these balls to be bonded together without interpenetration.** According to your suggestion, I will try to adjust the contact radius and spring constant. I want to show one previous aborted case. Case 1 (calculation is aborted when the red ball (shown in the above picture) contacts the jetting).
![Case 1](https://user-images.githubusercontent.com/110468396/215638456-cdd03471-4238-4c7a-97a0-fc325d25bebe.png)
