### ISSUE TITLE
Failure on changing mesh density, horizon value

### ISSUE THREAD

**Issue by Jacob328** [peridigm/peridigm#300]
I have recently installed Peridigm on my university's computer cluster and can successfully run simple cases (for instance, the disk impact example). However, when I try to refine the disk mesh, model a thicker disk, and/or increase the peridynamic horizon, the simulation fails with something resembling the attached error code. I have not been able to identify what specific changes to the model lead to failure- only that the above mentioned modifications generally lead to error messages like the one attached.

The error message that I attached corresponds to a peridynamic model that is similar to the disk impact example case (same peridynamic horizon), but uses a thicker disk (0.012 m rather than the 0.0025 m thickness used in the example file) and a slightly more refined mesh for the sphere and target (refined by a factor of around 1.3).

Does anyone have insight into what may be the source of the error? I will add that I do not think it as a memory error as the cluster I am using reports a general error rather than an out of memory error. Further, I have taken steps to monitor the memory usage, and it seems I am reserving more memory for the simulation runs than is being used (though I am not very well versed in such analyses and could easily be mistaken).

Any help or suggested locations to direct this question would be hugely appreciated!  

**Slurm's error message:** [SlurmOutMessage.txt](https://github.com/peridigm/peridigm/files/10709180/SlurmOutMessage.txt)

**Comment by andrisfreimanis** [comment]
Peridigm gives this error

** Warning: the selected contact search radius, 0.01, is large
** relative to the maximum element diameter (0.000639873).
** This may lead to the memory capacity being exceeded.

Could it be that the horizon is too large and you exceeded the memory available at the node, and the operating system killed the process?

Best regards
Andris

From: Jacob328 ***@***.***>
Sent: perjantai 10. helmikuuta 2023 16.05
To: peridigm/peridigm ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [peridigm/peridigm] Failure on changing mesh density, horizon value (Issue #300)


I have recently installed Peridigm on my university's computer cluster and can successfully run simple cases (for instance, the disk impact example). However, when I try to refine the disk mesh, model a thicker disk, and/or increase the peridynamic horizon, the simulation fails with something resembling the attached error code. I have not been able to identify what specific changes to the model lead to failure- only that the above mentioned modifications generally lead to error messages like the one attached.

The error message that I attached corresponds to a peridynamic model that is similar to the disk impact example case (same peridynamic horizon), but uses a thicker disk (0.012 m rather than the 0.0025 m thickness used in the example file) and a slightly more refined mesh for the sphere and target (refined by a factor of around 1.3).

Does anyone have insight into what may be the source of the error? I will add that I do not think it as a memory error as the cluster I am using reports a general error rather than an out of memory error. Further, I have taken steps to monitor the memory usage, and it seems I am reserving more memory for the simulation runs than is being used (though I am not very well versed in such analyses and could easily be mistaken).

Any help or suggested locations to direct this question would be hugely appreciated!

Slurm's error message: SlurmOutMessage.txt<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fperidigm%2Fperidigm%2Ffiles%2F10709180%2FSlurmOutMessage.txt&data=05%7C01%7CAndris.Freimanis%40vtt.fi%7Ca102b3cd3d374012536b08db0b809ae6%7C68d6b592500843b59b0423bec4e86cf7%7C0%7C0%7C638116419209393771%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=aoeYqu212vZRQdom52%2FZv9PtAPh7DOv4Dfrfj0tkHvY%3D&reserved=0>

-

**Comment by Jacob328** [comment]
The contact search radius is separate from the peridynamic horizon thought, correct? I have tried cases in which I run the simulation with a reduced contact search radius such that the warning you refer to does not appear, but in most cases of mesh refinement and/or target thickness increase, I get a similar error message. Perhaps I could try to identify the simplest case in which the error message appears without the cited warning message and provide that for reference?

**Comment by Jacob328** [comment]
One of the error messages I got in running a similar simulation indicated a segmentation fault error. Increasing the allocated memory, even dramatically, does not seem to address the issue. I am thinking that, as you suggested (@oldninja and @andrisfreimanis), maybe the issue has to do with too many peridynamic nodes in a neighborhood, but maybe it is not just a memory issue. Instead (this is wild conjecture), maybe I am requesting more nodes per neighborhood than allowed by Peridigm in the sense that I am trying to store nodes in an array position that exceeds some hard limit on array dimensionality.

Is there a fixed limit to the number of nodes allowed in a neighborhood or, in some other way, do you think it is possible that my model is trying to add an array index beyond some Peridgm array size?

I am sure this is unrelated, but I notice there is the statement "max of 40 elements per node" on line 10 of [SlurmOutMessage.txt](https://github.com/peridigm/peridigm/files/10709180/SlurmOutMessage.txt). I am not quite sure what limitation that imposes.

**Comment by oldninja** [comment]
I don't think there is a hard-coded limit. However, I would say you don't want to model more than 4 or 5 times ypur horizon because the computational cost becomes too high.

**Comment by djlittl** [comment]
As @oldninja said, if the horizon is large relative to the mesh spacing, you can run out of memory because the number of bonds grows quickly as this ratio increases.  This is also true for contact.  Peridigm uses basically the same neighbor list data structures to store potential contact interactions (i.e., pairs of nodes that are within the contact search radius).  So if you have a contact search radius that is much larger than the mesh spacing, you could run out of memory or potentially run out of signed integers and end up with a bogus array index.  I suggest setting both these ratios to roughly 3.  If that works, you could try increasing it from there, if desired.

**Comment by Jacob328** [comment]
Thanks so much to everyone that has responded. I have been more or less successful at resolving the error messages like that posted in my initial message, so I'll close this "issue" thread shortly. In the future, if I run into problems working with Peridigm, is it preferable to direct questions as an issue here on Github or via the Peridigm email, peridigm-users@software.sandia.gov?

**Comment by oldninja** [comment]
I would say post them here and we will try to answer them as soon as possible.

**Comment by djlittl** [comment]
Agreed, GitHub is preferred over the Peridigm mailing lists.

**Comment by Jacob328** [comment]
Okay, great; thanks again for your help!

**Comment by Jacob328** [comment]
Closed.
