### ISSUE TITLE
Strain Energy Output

### ISSUE THREAD

**Issue by Jacob328** [peridigm/peridigm#305]
I'd like to output the global strain energy of a simulation that uses the elastic correspondence material model. However, when I specify

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Output_2:
      Output File Type: "ExodusII"
      Output Filename: "CoarsenedSphere"
      Output Frequency: 1000
      Output Variables:
          Global_Kinetic_Energy: true
          **Global_Strain_Energy: true**
          Global_Linear_Momentum: true
          Global_Angular_Momentum: true
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

I get the following error:

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Error, the parameter {name="Global_Strain_Energy",type="bool",value="1"}
in the parameter (sub)list "Peridigm->Output_2->Output Variables"
was not found in the list of valid parameters!

The valid parameters and types are:
  {
    "Element_Id" : bool = 0
    "Block_Id" : bool = 0
    "Horizon" : bool = 0
    "Volume" : bool = 0
    "Model_Coordinates" : bool = 0
    "Coordinates" : bool = 0
    "Displacement" : bool = 0
    "Velocity" : bool = 0
    "Acceleration" : bool = 0
    "Temperature" : bool = 0
    "Concentration" : bool = 0
    "Temperature_Change" : bool = 0
    "Flux_Divergence" : bool = 0
    "Concentration_Flux_Divergence" : bool = 0
    "Force_Density" : bool = 0
    "Contact_Force_Density" : bool = 0
    "External_Force_Density" : bool = 0
    "Proc_Num" : bool = 0
    "Hourglass_Force_Density" : bool = 0
    "Deformation_Gradient" : bool = 0
    "Left_Stretch_Tensor" : bool = 0
    "Rotation_Tensor" : bool = 0
    "Shape_Tensor_Inverse" : bool = 0
    "Unrotated_Cauchy_Stress" : bool = 0
    "Cauchy_Stress" : bool = 0
    "Unrotated_Rate_Of_Deformation" : bool = 0
    "Partial_Stress" : bool = 0
    "Force" : bool = 0
    "Contact_Force" : bool = 0
    "Number_Of_Neighbors" : bool = 0
    "Radius" : bool = 0
    "Kinetic_Energy" : bool = 0
    "Global_Kinetic_Energy" : bool = 0
    "Linear_Momentum" : bool = 0
    "Global_Linear_Momentum" : bool = 0
    "Angular_Momentum" : bool = 0
    "Global_Angular_Momentum" : bool = 0
  }

Throw number = 1
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

Do I need to manually add the output variable Global_Strain_Energy to the list of valid output variables?

**Comment by djlittl** [comment]
Alas, it's more work than that.  You'll need to add a function to that material model to compute the stored elastic energy (i.e., strain energy).  Peridigm would be happy to compute the global sum, but the strain energy function needs to be implemented for whatever material model you are using.  If I recall correctly, I think it's only implemented for the LPS model (called "Elastic" in Peridigm).  Implementing the strain energy function for the LPS model was straightforward because there is a formula available from the literature.

Note that you're opening a can of worms with the correspondence models.  The stress/strain relationship is dictated only by the approximate deformation gradient.  This works if there are no broken bonds.  But if bonds break, the stored elastic energy will not change in a physically meaningful way.  It should go down, but if the deformation gradient doesn't change then the stored elastic energy won't change.  These values will change slightly when bonds break, but that's just a function of the nodes moving around a bit.  This is a known flaw with the correspondence model method and bond failure, it's not a flaw in Peridigm per se.

People (including me, I admit) often take liberties when combining material models with bond failure models.  The critical stretch bond failure law is truly consistent with only the bond-based elastic material model.  While simulation results are often plausible/useful, the inconsistencies will probably become apparent as you look closely at the stored elastic energy.

**Comment by Jacob328** [comment]
Thanks so much for your detailed response, David. Any improvement in my understanding of the current state of the Peridigm code (and/or peridynamics in general) is very useful. On that note - I've been familiarizing myself with Peridigm using the V1.0.0 2012 Sandia Technical Report: "Peridigm Users' Guide" and the 2018 Peridigm user guide developed by Martin Rädel and Christian Willberg from the German Aerospace Group. Other than the code itself (which at a first glance does seem to be well documented), are there any additional recommended user-guide-type resources?

**Comment by djlittl** [comment]
I'm a co-author on a manuscript titled "The Peridigm Meshfree Peridynmics Code" which is currently under review.  We're optimistic that it will be published this year.  That should help, basically replacing the outdated original user manual.

But none of these sources would have enough detail to help with the specific issues in this thread.  Posting to GitHub is probably the best bet.

**Comment by Jacob328** [comment]
Exciting! I'll keep my eye out for the paper.
