### ISSUE TITLE
make test failed

### ISSUE THREAD

**Issue by mashhadi18** [peridigm/peridigm#31]
Hi all,
I have recently installed Peridigm v1.5.0 and loaded the following module in my user account:
module load compiler/gcc/4.9 openmpi/1.10 boost/1.59 phdf5/1.8 pnetcdf/4.4 matio/1.5 trilinos/12.6
This is also my cmake command

cmake \
-D CMAKE_BUILD_TYPE:STRING=Release \
-D Trilinos_DIR:PATH=/util/opt/trilinos/12.6/openmpi/1.10/gcc/4.9 \
-D CMAKE_C_COMPILER:STRING=/util/opt/openmpi/1.10/gcc/4.9/bin/mpicc \
-D CMAKE_CXX_COMPILER:STRING=/util/opt/openmpi/1.10/gcc/4.9/bin/mpicxx \
-D BOOST_ROOT=/util/opt/boost/1.59/gcc/4.9 \
-D CMAKE_CXX_FLAGS:STRING="-O2 -Wall -std=c++11 -pedantic -Wno-long-long -ftrapv -Wno-deprecated" \
-D CMAKE_EXE_LINKER_FLAGS="-L /util/opt/boost/1.59/gcc/4.9/lib -L/util/opt/hdf5/1.8/openmpi/1.10/gcc/4.9/lib" \
/work/bobaru/jmm/Peridigm_061917

after using "make -j 4", I use "make test" and the testing procedure stops after 97 tests with some passed and failed tests. Here is my message from Testing/Temporary: [http://go.unl.edu/txr9](url)

Please let me know what I should change to get all tests passed. Thanks

**Comment by djlittl** [comment]
Can you provide a log file from one of the failing tests?  Go under the test directory in your build directory and drill down into one of the failing tests.  There should be a .log file that hopefully shows what went wrong.

**Comment by mashhadi18** [comment]
Please download these links which are from two different directories

http://go.unl.edu/3rwy
http://go.unl.edu/ft6n

**Comment by mashhadi18** [comment]
Please download these links which are from two different directories

http://go.unl.edu/3rwy
http://go.unl.edu/ft6n

**Comment by djlittl** [comment]
Looks like you have some sort of mpi error.  As I'm sure you can see, it says

--------------------------------------------------------------------------
Open MPI failed to open the /dev/knem device due to a local error.
Please check with your system administrator to get the problem fixed,
or set the btl_sm_use_knem MCA parameter to 0 to run without /dev/knem
support.

  Local host: login
  Errno:      2 (No such file or directory)
--------------------------------------------------------------------------
 
I don't think this is a Peridigm issue per se.

I googled the above error message and it looks like you can set:

--mca btl_sm_use_knem 0

which I assume just goes after the mpirun command on the command line.  This is not a Peridigm setting.  I don't know what it is exactly, but it appears to be a feature of the MPI that you're using.

What type of machine are you running on?  If you're on a cluster, are you sure you're allowed to fire off an mpi job directly from the command line?

Can you successfully run any type of mpi program?

The files that Peridigm says it can't open are definitely there in the test directory.

**Comment by mashhadi18** [comment]
Actually, I ran peridigm with a single core and it worked with no problem.  I will ask about mpi from our cluster administrator and will update you here.

**Comment by djlittl** [comment]
Sounds good.  It's possible that you're required to use a job submission script to fire off an mpi job.  Just a thought.
