### ISSUE TITLE
Segmentation Fault during simulation

### ISSUE THREAD

**Issue by bdas123** [peridigm/peridigm#351]
Hello, I read a previous issue that dealt with the segmentation fault. 

However, it appeared that the user encountered the error at the beginning of the simulation because they had not decomposed the simulation using Trilinos. 

I encounter the segmentation error while the simulation is running. 

I have attached the file to this document. 

[RR.pdf](https://github.com/peridigm/peridigm/files/12425759/RR.pdf)

**Comment by djlittl** [comment]
I don't see any information in the output stream to indicate what went wrong.  The MPI errors are likely a result of one process failing, after which the other processes fail because the MPI communications are no longer working.

A few thoughts on troubleshooting:

- Is this error repeatable?  Does it always fail at the same point?
- Is the error repeatable on a different number of MPI ranks?
- You presumably have simulation output (.e files) up to that point that it fails.  Do the results look sane?  If the simulation goes haywire, it may be generating NaNs or similar, causing a failure.
- Any indication from the platform itself that you have hit a time limit, run out of memory, or any other issue that would case the simulation to abort?
