### ISSUE TITLE
finding a software

### ISSUE THREAD

**Issue by Bapun-kumar** [peridigm/peridigm#353]
Which software is used to view these crack propagations and what is the file format is needed for that software?
![Screenshot 2023-09-04 111106](https://github.com/peridigm/peridigm/assets/124157204/70160e8e-c144-4f9d-87b4-0b95d8065fe8)

**Comment by oldninja** [comment]
That looks like a matlad or matplotlob contour...

**Comment by djlittl** [comment]
Peridigm output is in exodus format (.e).  The exodus format is build on netcdf, which can be read by MATLAB and similar.  This works but is not super user friendly because those codes treat the exodus files only as netcdf files, hence the association of field names with specific fields and other conveniences get lost.

The ParaView visualization code is freely available at paraview.org and does a great job with exodus files.  I suggest you give that a try.

**Comment by Bapun-kumar** [comment]
> Peridigm output is in exodus format (.e). The exodus format is build on netcdf, which can be read by MATLAB and similar. This works but is not super user friendly because those codes treat the exodus files only as netcdf files, hence the association of field names with specific fields and other conveniences get lost.
> 
> The ParaView visualization code is freely available at paraview.org and does a great job with exodus files. I suggest you give that a try.

Actually I am currently using Paraview software and it's nice but those pictures looks fascinating and more eye catching than Paraview. Can I get these pictures in Abaqus by importing exodus format?

**Comment by oldninja** [comment]
You can create the same with ParaView. Look at the different options to post-process your data. ParaView usually allows you to have more control on the quality of the pictures than Abaqus CAE.

**Comment by diehlpk** [comment]
Yes, Paraview or ViSit are used for PD simulations. There are some papers about advanced visualization techniques available.
