### ISSUE TITLE
stress-strain values, mesh refinement

### ISSUE THREAD

**Issue by yilmaz122** [peridigm/peridigm#37]
Dear all, 
Thanks a lot for the great informations that you shared already.
I have 2 issues.
First, I was just planning to get stress and strain values for a given tensile-test example. I could not get it yet.
Second, I could not understand how and where I can change mesh density for tensile-test or any other example.

Thank you.
Yilmaz

**Comment by smenon92** [comment]
Are you talking about the example given in Peridigm download file? I thought it came with strain outputs enabled.

**Comment by yilmaz122** [comment]
This is the one that you are writing about?

Output
    Output File Type "ExodusII"
    Output Filename "tensile_test"
    Output Frequency 1
    Output Variables
      Displacement "true"
      Velocity "true"
      Element_Id "true"
      Proc_Num "true"
      Force_Density "true"
      Hourglass_Force_Density "true"
      Force "true"
      Volume "true"
      Gage_Top_Initial_Position "true"
      Gage_Bottom_Initial_Position "true"
      Gage_Top_Displacement "true"
      Gage_Bottom_Displacement "true"
      Top_Reaction_Force "true"
      Bottom_Reaction_Force "true"
      Deformation_Gradient "true"
      Cauchy_Stress "true"
      Radius "true"
      Number_Of_Neighbors "true"
      Neighborhood_Volume "true"

**Comment by smenon92** [comment]
Yes. Can't you view this on Paraview?

Also, regarding meshing: Peridigm doesn't do its own meshing from scratch. It accepts a discretization file in .g(Exodus) or .txt format. You can create .g discretizations using CUBIT/Trelis. You'll need Trelis to modify the .g file provided with the tensile test example. 
[(https://peridigm.sandia.gov/content/running-simulations-peridigm]
[](https://peridigm.sandia.gov/content/running-simulations-peridigm)

**Comment by yilmaz122** [comment]
I see Cauchy_Stress model. But my plan was to compare with the model that I get from Abaqus.

First time I hear about CUBIT/trellis.

**Comment by smenon92** [comment]
I'm afraid I don't understand what the problem is If you can see the stress.

Did you follow the link I provided? It explains how Peridigm performs discretization. csimsoft provides a trial version of Trelis for 30 days, you can check it out.

**Comment by yilmaz122** [comment]
Yes. I made a request for trial version for Trelis. And trying to follow the link for meshing.

**Comment by ilyasst** [comment]
Hi !

Since Trelis is pretty expensive, I worked with a colleague (Patrick Diego)
on a tool to convert Gmsh meshes to Exodus.
Gmsh is a free and open source software to mesh parts.

The tool is here: https://github.com/IaPCS/gmsh-exodus-converter
Feel free to use it !

Let us know if you have any issues with it.

Ilyass
http://iltabiai.github.io
(from phone)

**Comment by smenon92** [comment]
`Hi !

Since Trelis is pretty expensive, I worked with a colleague (Patrick Diego)
on a tool to convert Gmsh meshes to Exodus.
Gmsh is a free and open source software to mesh parts.

The tool is here: https://github.com/IaPCS/gmsh-exodus-converter
Feel free to use it !

Let us know if you have any issues with it.

Ilyass
http://iltabiai.github.io
(from phone)`

Thanks! I'll look into it,

**Comment by yilmaz122** [comment]
Hello again,

If I am not missing there is no strain values for given tensile-test example right? If so how can we get that values for given example? 

Thanks.
Ali

**Comment by yilmaz122** [comment]
Hello, 

I was expecting to get Strain values for a given tensile-test example from GradientOfUnstructuredDataSet1 using Displacement. But it does not work. Am I missing something?

Thanks.
Yilmaz
