### ISSUE TITLE
Plane Stress/Strain 2D Test - curve mismatch

### ISSUE THREAD

**Issue by efrainhr** [peridigm/peridigm#381]
Trying to simulate tension on a 2D domain. Following Discussion #299, I tried the elastic bond based 2D test/example. When I ran the post-process script, I noticed that the calculated stress did not match the ideal case (matches if I times x2.5). Tried refining the mesh, but that made it worse! Am I not understanding the plane stress method? I'm simply running the files/scripts in test/verification/ElasticBondBased/ElasticBondBased2DPlaneStress. Thoughts/suggestions? Thanks! 
This is what I get. 
![image](https://github.com/user-attachments/assets/7a80977d-d9b1-4b05-887f-2f8f9858cfa6)

**Comment by johntfoster** [comment]
Unfortunately, the developer who made the commit that added these features
doesn't appear to have an active Github account any longer.  There is a
note that says:

- Remark: The provided height must match the one used to calculate the
volume of the discretization!

So if you change the discretization, I guess you also need to change the
height parameter. Since this was a community contribution to Peridigm, I
think you have to regard it as experimental. You may need to add your own
plane stress/strain implementations.

I'm skeptical of these models and would refer you to the plane
stress/strain models described in Chapter 6 of the "Handbook of Peridynamic
Modeling" which are state-based models, not bond-based.

**Comment by efrainhr** [comment]
Gotcha. Thanks for the feedback. I'll explore the state-based model/handbook further. Somewhat new to peridynamics, so still learning. Thanks!

**Comment by oldninja** [comment]
> Tried refining the mesh, but that made it worse! Am I not understanding the plane stress method? I'm simply running the files/scripts in test/verification/ElasticBondBased/ElasticBondBased2DPlaneStress. Thoughts/suggestions? Thanks!

@jritta do you have any suggestions for this?
