### ISSUE TITLE
Outputting the history file takes forever in my simulation

### ISSUE THREAD

**Issue by masoudbehzadinasab** [peridigm/peridigm#4]
Hi there. 

I have been running some simulations using peridigm on a granular particles field.
```
Number of coordinates per node       =           3
Number of nodes                      =      198860
Number of elements                   =      198860
Number of element blocks             =        6512
Number of nodal point sets           =        6512
Number of element side sets          =           0
Number of time steps = 9300
```
I am tracking down the particles velocities and displacements by the closest PD node to the center of the particle. I use the global variables to write them down to the output history file. 

The problem here is that most time of the run time is devoted to the outputting part. Below is the run time for a case where I output the history file every 10 time steps (930 total).
```
Wallclock Time (seconds):
                                        Min            Max            Ave
  Total                               3e+04          3e+04          3e+04
  Rebalance                         1.7e+03        1.7e+03        1.7e+03
  Output                              4e+03        1.7e+04        4.3e+03
  Internal Force                    3.2e+02        3.3e+02        3.3e+02
  Initialize Contact Maps             0.001         0.0011         0.0011
  Gather/Scatter                    9.9e+03        2.3e+04        2.3e+04
  Apply Kinematic B.C.                  2.4             83             27
  Apply Initial Conditions             0.26           0.27           0.27
  Apply Body Forces                     0.1           0.11           0.11
```
And the following is for a case where I output the history file every other time step (4650 total).
```
Wallclock Time (seconds):
                                        Min            Max            Ave
  Total                             8.5e+04        8.5e+04        8.5e+04
  Rebalance                         1.8e+03        1.8e+03        1.8e+03
  Output                            6.4e+03        7.1e+04        7.8e+03
  Internal Force                    3.2e+02        3.3e+02        3.3e+02
  Initialize Contact Maps             0.001         0.0011         0.0011
  Gather/Scatter                    9.9e+03        7.5e+04        7.3e+04
  Apply Kinematic B.C.                  2.4             85             27
  Apply Initial Conditions             0.26           0.27           0.27
  Apply Body Forces                     0.1           0.12           0.11
```
As you can see the total run time is increased from 8 hours to 23 hours!! (As I noticed, the major time which is related to making that .h file is not included here.)

I am not sure if Peridigm is optimized in terms of global variables. 

Is there any way that I can generate the history file similar to the way that the exodus file (.e) is generated? As I have realized, the exodus file is generated by each processors and at the end, they can combined using epu. However, there is only one history file generated by the processor #0. 

Thanks so much for your time. I look forward to hearing back.

Best
Masoud Behzadinasab
PhD Student in Engineering Mechanics
UT Austin

**Comment by johntfoster** [comment]
I believe this is because we are doing a reduce and/or gather command on all the variables whether they are truly global or not.  For example, if one wants to output total grid kinetic energy a reduce call is required; however, if you are tracking the displacement, velocity, etc. of a single point through time, this could potentially be handled and output by each multiple processors that manage the tracking of some local points.

**Comment by djlittl** [comment]
A few thoughts:

If I'm reading this correctly, you have 6512 global variables (one per block).  Peridigm really wasn't designed for this many global variables, so I'm not too surprised to see poor performance.  For each global variable, I'm assuming you have a separate compute class.  The code loops over compute classes when output is triggered, meaning that they get evaluated one at a time.  And as John said, there's some global communication involved.  I don't think it's the output per se that's slow, I think it's the compute class evaluations, which are triggered by output (I could be wrong on that, profiling the code is the best way to know for sure).

Evaluation of the compute classes is independent of whether you output to a .h or a .e file.  I don't think you'll have much luck trying to speed things up by outputting to a .e file.

Outputting every 10 time step in an explicit dynamics calculation is a considerable amount of output.  No matter what you do, I suspect that output will be a significant portion of the run time.  But I do think you can speed things up considerably.

One experiment to try is to write a .e file containing the positions of all the points in the model instead of a .h file.  This would give you good information.  If it's significantly faster, that suggests that I/O is not really the problem and that it's the compute classes that are killing you.  If things run better with a .e file and no compute classes, you could always just post-process the .e file to extract the displacements that you're after.

You could also think about writing your own compute class.  I think you could come up with a way to process all your output in a single compute class, which might speed things up considerably.  You would be free to do somewhat hackish things like write a text file from each processor and eliminate the need for any parallel communication.

Do you really need 6000+ blocks?  (You might actually need them, not sure.)  The code in general will probably run significantly faster if you ran this simulation as a single block.  Would be worth a try, just as an experiment.

Dave

**Comment by johntfoster** [comment]
@djlittl Is the compute class only called when output is requested (i.e. every X `*.h` output dump timesteps?).

He needs the 6000+ blocks, these are the granular material simulations and he needs to call  `Omit_Bonds_Between_Blocks`.

**Comment by djlittl** [comment]
I'm 95% sure that the compute classes are called only when there is output to file.  I took a quick look at the code, and it looks like the only call to the compute classes is

peridigm->computeManager->compute(blocks);

which is in the OutputManager_ExodusII::write() function.  So, the compute classes are being called by the output manager, which only gets called when writing to disk.

I recall there were discussions at one point about making it possible to have compute classes that are called at every time step and other compute classes that are called only at output.  But I don't think this ever got past the discussion stage.  For the majority of cases, you really want it called only at output.  But if you wanted to, say, integrate a quantity over time, you'd need to call the compute class at every time step.  Keep in mind that many of the compute classes are on the order of a constitutive model in terms of expense, so calling them at every time step is pretty costly.

Another thing that never got past the discussion stage is the ability to use a shell mesh to define bond cutting planes.  That would be quite handy here, as it would allow the simulation to be run as a single block.  I suppose one could also implement a "omit bonds between node sets" feature or some such that does what we're doing now but does not require separate blocks.

**Comment by masoudbehzadinasab** [comment]
@djlittl Dr. Littlewood - Thank you so much for helping me understand what the real problem is. I will continue thinking to come up with a smart way for outputting the desired variables.

Best
Masoud
