### ISSUE TITLE
Bond filters

### ISSUE THREAD

**Issue by mbhzdi** [peridigm/peridigm#41]
Dear All, 

The bond filtering feature of peridigm does not see those neglected bonds as broken (damage), right? I was wondering what strategy would be good to implement in the code for including those neglected/broken bonds as initial damage, for visualization purposes. In its current form, I was not able to find a way to visualize a crack instantiated with bond filters, in its initial configuration.

Thanks for your time.

Masoud

**Comment by djlittl** [comment]
Masoud,

Just wanted to reply to confirm what you’re observing.  The bond filters do not break the bonds, they cause the bonds to not be created in the first place.  There is a difference between these two operations, because of things like the weighted volume, which is computed in the reference configuration under the assumption that all the bonds are valid unbroken bonds.  Also, things like scalar damage (percentage of bonds that are broken) would come out differently if bond filters broke bonds as opposed to causing them not to exist in the first place.

To visualize the effect of bond filters, I use the Number_Of_Neighbors variable, which you can simply request as an output variable.  If you have a pre-crack or similar, it will be visible in Paraview when visualizing the number of neighbors, since the bond filter reduce the number of neighbors.

The code for bond filters is fairly deeply embedded in Peridigm.  Changing the behavior so that the filters break the bonds as opposed to causing them not to exist would probably be tricky.  You would probably have better luck writing a custom damage law that breaks bonds at initialization based on some user criteria (like bond filters).

Dave

**Comment by mbhzdi** [comment]
Hi Dr. Littlewood,

Thank you so much for your explanation. I see what is happening there. The Number_Of_Neighbors variable should do the job for me. 

Thanks a lot!

Masoud

**Comment by MDBrothers** [comment]
I probably added the feature you're talking about in ACTs version.

**Comment by mbhzdi** [comment]
That's true! Thanks @MDBrothers

**Comment by silversol1** [comment]
Dear All,
I know that the bonds can be filtered using a plane in Peridigm, but, it is relatively difficult to apply for complex geometries. Therefore, I was wondering if it is possible to create filter bonds only between two specific blocks whilst the other blocks still have bonds. Thank you in advance for your consideration.

**Comment by djlittl** [comment]
For some reason, I’m not able to see this comment on GitHub.  Hopefully my response goes through.

There is a feature called “Omit Bonds Between Blocks” that is part of the Discretization section in the input deck.  See Contact_Ring.xml in the test directory for an example.

Unfortunately, it appears that the only allowable values for “Omit Bonds Between Blocks” are “All” and “None”, meaning that the only thing you can do with “Omit Bonds Between Blocks” is turn off all bonds between all blocks.  Which may or may not be what you want to do.

I dug into the code (Peridigm_ExodusDiscretization.cpp, Peridigm_TextFileDiscretization.cpp), and it looks like most of the code is there to allow users to specify that bonds should be omitted between certain blocks.  See the function PeridigmNS::ExodusDiscretization::filterBonds().  What needs to be done is some string parsing to properly set the blockBondingMatrix, which basically sets either true or false for bond creation between all pairs of blocks.  Assuming this works, we’ll want at least one test for the test repository that exercises this feature.  If you or someone else has the time to implement/test this feature and submit a pull request, I can look it over and add it to the main branch.

Dave
