### ISSUE TITLE
Failure during Installation

### ISSUE THREAD

**Issue by heinzlmeier** [peridigm/peridigm#55]
Hello!   I try to install Peridigm with Ubunt 16.4 in a Virtual Box    but I receive following error.

Hope someone can help me.

yours Lukas

![failure](https://user-images.githubusercontent.com/39583385/40485184-2946e918-5f5e-11e8-80b0-bf15bea09abd.png)

**Comment by MDBrothers** [comment]
You didn't successfully link to any Boost libraries.

On May 24, 2018 7:25 AM, "heinzlmeier" <notifications@github.com> wrote:

Hello! I try to install Peridigm with Ubunt 16.4 in a Virtual Box but I
receive following error.

Hope someone can help me.

yours Lukas

[image: failure]
<https://user-images.githubusercontent.com/39583385/40485184-2946e918-5f5e-11e8-80b0-bf15bea09abd.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/peridigm/peridigm/issues/55>, or mute the thread

**Comment by MDBrothers** [comment]
Yeah looks like you're missing the boost regex component at least.

**Comment by heinzlmeier** [comment]
After the bootstrap.sh --with-icu --prefix=/home/heinzlmeier/local/boost_1_62_0            
the System answers :   Unicode/ICU support for Boost.Regex?... not found

Did I use the wrong Boost Version ?

**Comment by djlittl** [comment]
I don't think you need the "--with-icu" option.  You should try running the bootstrap script again without it.

**Comment by heinzlmeier** [comment]
I tried it without  "--with-icu"  but the same error occurs. --> I run the bootstrap script again 
 ./bootstrap.sh --prefix=/home/heinzlmeier/local/boost_1_62_0

Additional Information
First I load the following packages ( zliblg-dev, curl, libblas-dev, liblapack-dev, liblapack-dev, libx11-dev, cmake)
and I use following versions ( openmpi-2.0.1, boost_1_62_0, hdf5-1.8.15-patch1, netcdf-c-4.3.3.1 and trilinos-12.0.1-Source

**Comment by djlittl** [comment]
Can you provide the full error message?  I don't understand why you'd still be getting the error "Unicode/ICU support for Boost.Regex?... not found" if you are not enabling ICU.

**Comment by heinzlmeier** [comment]
The complete message looks like this.,

![boost](https://user-images.githubusercontent.com/39583385/40564276-5b92f8a2-6068-11e8-86ae-bb9df55f0855.png)

**Comment by heinzlmeier** [comment]
Problem solved :)

--with-icu=PATH_to_ICU_LIB

**Comment by tjcuxhh** [comment]
Hello!  Could you share your install getdit file for a reference.   Thanks very much.
