### ISSUE TITLE
libQuickGrid.a(QuickGrid.cxx.o) error

### ISSUE THREAD

**Issue by berraw** [peridigm/peridigm#81]
Hi,
I am a newbie about peridigm. Actually, I am trying to install the Peridigm 1.5.0. I received an error as below. Thanks for help

...
[ 60%] Linking CXX executable utPeridigm_PdQuickGridDiscretization_MPI_np2
../../mesh_input/quick_grid/libQuickGrid.a(QuickGrid.cxx.o): In function `QUICKGRID::getMeshGenerator(unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)': QuickGrid.cxx:(.text+0x9b9d): undefined reference to `Teuchos::updateParametersFromYamlFile(std::__cxx11::basic_string<char, std::char_traits, std::allocator > const&, Teuchos::PtrTeuchos::ParameterList const&)'
collect2: error: ld returned 1 exit status
src/io/discretization/unit_test/CMakeFiles/utPeridigm_PdQuickGridDiscretization_MPI_np2.dir/build.make:1851: recipe for target 'src/io/discretization/unit_test/utPeridigm_PdQuickGridDiscretization_MPI_np2' failed
make[2]: *** [src/io/discretization/unit_test/utPeridigm_PdQuickGridDiscretization_MPI_np2] Error 1
CMakeFiles/Makefile2:628: recipe for target 'src/io/discretization/unit_test/CMakeFiles/utPeridigm_PdQuickGridDiscretization_MPI_np2.dir/all' failed
make[1]: *** [src/io/discretization/unit_test/CMakeFiles/utPeridigm_PdQuickGridDiscretization_MPI_np2.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by djlittl** [comment]
Sorry, this one is my fault.  This unit test requires YAML, and my guess is that you built Trilinos without yaml support.  I should have put a conditional in the CMakeLists.txt file such that this test doesn't build unless YAML is present.  I'll add that soon.

I am in the process of updating the build system, and most likely YAML will be a required package sometime soon.

For now, you can either 1) install YAML and rebuild Trilinos, or 2) just run "make Peridigm", which will cause the build system to only build Peridigm and not the unit tests.

I should be able to fix the build system today or tomorrow so that this build error goes away when building without YAML.

If anyone has an opinion as to whether YAML should be required, let me know.  The examples have already been converted to .yaml input files, which makes me think YAML should be required.

**Comment by berraw** [comment]
Actually, I built Trilinos with yaml support. But it is clear that I made a mistake during installation of Trilinos. I will try to install Trilinos again. Thanks for quick reply.

**Comment by johntfoster** [comment]
@djlittl I'm okay with making it a required package.  yaml-cpp is easy to build/install and the input decks are infinitely more readable in .yaml format.
