### ISSUE TITLE
Horizon manager receives non-double data type and results in an error

### ISSUE THREAD

**Issue by uppatispr** [peridigm/peridigm#9]
When you use a .peridigm format for the input deck, there's no need to specify data types for values you provide as simulation parameters. There's a bug in the parser for the .peridigm format input deck that incorrectly converts any numbers without a decimal component into a non-double data type. This results in an error during runtime, because horizon manager cannot find a double data type value and hence results in the following error: 

-- Peridigm
-- version 1.5.0 (Dev)

/Users/Sai/research_software/Source-Codes/peridigm-official/src/core/Peridigm_HorizonManager.cpp:77:

Throw number = 1

Throw test that evaluated to true: !hasConstantHorizon && !hasVariableHorizon

**** Error parsing horizon information!  No horizon definition found!

Wallclock Time (seconds):
  Total            0.011

The type of values I'm talking about are 12, 36.0, 45.00 etc. These values would not be considered double type when they are parsed into xml format. On the other hand, values such as 11.05, 1.2 etc are fine, because they are attributed to the double data type. 

This seems like a simple enough bug to fix, but I'm just not sure where to look. If someone can direct me on which specific file to edit, I can try and fix the error and perhaps submit a pull request.

**Comment by djlittl** [comment]
Sai,

I'm not 100% certain that I understand what you're saying.  Are you saying that the .peridigm parser will interpret

2

as an integer, and

2.0

as a floating-point number?

I acknowledge that this is an inconvenience in the example you provide, but I don't really think it's a bug.

The root cause of the behavior is that the input deck parser reads data from the either a .peridigm or .xml file and writes to an internal data structure (specifically, a Teuchos::ParameterList).  This procedure has no knowledge of Peridigm internals.  For example, it has no knowledge that Horizon should be a floating-point number.  It just reads whatever you provide and populates the ParameterList.  In the case of the xml file, there is little chance for error, because the user is forced to spell out the data type (int, float, string, etc.).  In the case of the .peridigm file format, the user does not provide the type directly, and the parser is forced to guess the data type.  It makes sense to guess that "2" is an integer and "2.0" is a float.  The Peridigm error comes later, when Peridigm tries to access a floating-point value for Horizon from the ParamterList (which only has an int value).

Just my two cents.

Dave

**Comment by johntfoster** [comment]
I agree this is not a bug, per se, but rather an inconvienence.  However, in this case, I believe there is an easy fix.  Around line 74 of [Peridigm_HorizonManager.cpp](https://github.com/peridigm/peridigm/blob/master/src/core/Peridigm_HorizonManager.cpp), there are type checks for `<double>` and `<string>`, you could add one for `<int>` and if `True` perform a typecast of the value from `int` to `double`.

**Comment by djlittl** [comment]
Sure, that would definitely work, although you might need to query the Parameter list a few times because I believe the get() call throws an exception if it fails and no default value is provided.  I guess one could write a wrapper utility function to get either an int or float value from a ParameterList. Or the .peridigm parser could insert both an int and a float version of the parameter into the ParameterList when it creates it (bad idea, but would fix this particular glitch).

To me, these fixes seem a bit dubious.  Making things more convenient for the user when inputting the horizon seems harmless, but then is someone going to do this everywhere in the code where a float is needed in the input deck?

Seems like something reasonable people can disagree on, but I don't see a problem with requiring the user to input a proper float (e.g., 2.0 as opposed to 2).  I do think the error message in this case is a bit misleading though, since it implies that the horizon is missing and doesn't mention the required type.

On a different but related topic, if I had resources to put into input deck improvements, I'd first figure out a way to give a warning if the indentation is off and then I'd get rid of the required quotes around "true" and "false" for bool values.  Indentation mistakes in particular lead to generally unpredictable code failures, because as in this case the ParameterList gets constructed without error but required parameters can't be located downstream.

Dave

________________________________

**Comment by johntfoster** [comment]
I agree with Dave, we cannot do explicit type checking on every input, I updated the error message to be a little less dubious and am closing for now.

I have some ideas on how to make the input deck more robust.  Namely, I'm starting to think we should change the format once again to a YAML based format and use [yaml-cpp](https://github.com/jbeder/yaml-cpp) to basically parse the yaml and stuff the output into parameter lists.  A comparison of what a  YAML input deck would look like, when compared against the `*.peridigm` format is below:

`*.peridigm`
````
Verbose "false"
Discretization
  Type "Exodus"
  Input Mesh File "twist_and_pull.g"
Materials
  My Material
    Material Model "Elastic"
    Density 1.0
    Bulk Modulus 1.66173e12
    Shear Modulus 3.571e11
````

`*.yml`
````
Verbose: false
Discretization:
  - Type: "Exodus"
  - Input Mesh File: twist_and_pull.g
Materials:
  My Material:
     - Material Model: "Elastic"
    - Density: !!float 1
    - Bulk Modulus: 1.66173e12
    - Shear Modulus: 3.571e11
````

So not really much difference.  Notice the string quotes are optional and you can use explicit typing, see `Density`, if desired.  Also, exact indentation is not required.  Any objections to using YAML?  If not I can see if I can get someone to work on it.

**Comment by djlittl** [comment]
John,

I'm copying Andrew Bradley on this because I believe he's thought about this issue for other code projects.  Andrew, and thoughts on YAML for input deck parsing?

Assuming this is a widely used and relatively mature option, I'm for it.  The only concern is that we'd introduce yet another TPL.  On the other hand, if we got rid of the .peridigm parser, we'd lose the dependency on boost regex.  I don't recall if there are other places in the code where compiled boost libraries are used.  Would be great to eliminate this dependency all together.

John, thanks for taking the lead on the input deck.

Dave

________________________________

**Comment by uppatispr** [comment]
Hi Dr. Littlewood and John,

I apologize if my initial message wasn't clear. Suppose I want to use 12.00 as my horizon and I specify it exactly like this "12.00", the .peridigm parser interprets this as an integer, I believe. At least, I know that even though there is a decimal point and digits being specified after the decimal point, the parser doesn't interpret it as a double data type. Hence, it spits out the error that there's no horizon definition found. On the other hand, if I use "11.99", because there are non-zero digits after the decimal point, the parser identifies this number as a double, leading to no errors. 

Sai

**Comment by johntfoster** [comment]
@djlittl I believe that given the license of yaml-cpp is MIT, we could just roll it in and build it with Peridigm the way we used to do with muParser.  Also, regarding boost, I think there may be a few unit tests that haven't been converted, but that should be easy to finish up.  That alone (getting rid of boost) may be the motivation for me to get this done.  I'll open a new issue.
